// Copyright (C) 2026 Dave Moore
//
// This file is part of Sorcery.
//
// Sorcery is free software: you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the Free Software
// Foundation, either version 2 of the License, or (at your option) any later
// version.
//
// Sorcery is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
// A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// Sorcery.  If not, see <http://www.gnu.org/licenses/>.
//
// If you modify this program, or any covered work, by linking or combining
// it with the libraries referred to in README (or a modified version of
// said libraries), containing parts covered by the terms of said libraries,
// the licensors of this program grant you additional permission to convey
// the resulting work.

#include "resources/filestore.hpp"
#include "common/define.hpp"
#include "core/debug.hpp"
#include "resources/define.hpp"
#include <array>
#include <libgen.h>
#include <limits.h>
#include <sstream>
#include <stdexcept>
#include <system_error>
#include <unistd.h>

#ifdef __linux__
#include <limits.h>
#include <unistd.h>
#elif defined(_WIN32)
#include <windows.h>
#endif

Sorcery::FileStore::FileStore() {

	_base_path = _get_exe_path();

	if (_base_path.empty()) {
		throw std::runtime_error{
			"Unable to determine the Sorcery executable directory."};
	}

	_file_paths.clear();
	_required_files.clear();
	_directory_paths.clear();

	// Required Directories
	_add_directory(CONFIG_DIR);
	_add_directory(DATA_DIR);
	_add_directory(DOCUMENTS_DIR);
	_add_directory(GFX_DIR);
	_add_directory(SAVE_DIR);
	_add_directory(SFX_DIR);
	_add_directory(VFX_DIR);
	_add_directory(SAVE_DIR, SAVE_CHARACTERS_DIR, true);
	_add_directory(SAVE_DIR, SAVE_STATES_DIR, true);

	_add_path(CONFIG_DIR, CONFIG_FILE);

	// Generated by ImGui if it does not already exist.
	_add_path(CONFIG_DIR, IMGUI_INI_FILE, false);

	// Save Files (not required, as they may not exist yet)
	_add_path(SAVE_DIR, SAVE_GAME_FILE, false);
	_add_path(SAVE_DIR, SAVE_STATES_DIR, SAVE_STATE_FILENAME, false);

	// Data Files (required)
	_add_path(DATA_DIR, ITEMS_FILE);
	_add_path(DATA_DIR, LAYOUT_FILE);
	_add_path(DATA_DIR, MAPS_FILE);
	_add_path(DATA_DIR, MONOSPACE_1_APPLE2_FILE);
	_add_path(DATA_DIR, MONOSPACE_1_C64_FILE);
	_add_path(DATA_DIR, MONOSPACE_1_DOS_FILE);
	_add_path(DATA_DIR, MONOSPACE_1_MSX2_FILE);
	_add_path(DATA_DIR, MONOSPACE_5_DOS_FILE);
	_add_path(DATA_DIR, MONOSPACE_5_FMTOWNS_FILE);
	_add_path(DATA_DIR, MONSTERS_FILE);
	_add_path(DATA_DIR, PROPORTIONAL_FONT_FILE);
	_add_path(DATA_DIR, STRINGS_FILE);
	_add_path(DATA_DIR, TEXT_FONT_FILE);

	// Document Files (required)
	_add_path(DOCUMENTS_DIR, LICENSE_FILE);
	_add_path(DOCUMENTS_DIR, COMPILE_FILE);

	// Graphics Files (required)
	_add_path(GFX_DIR, BACKGROUNDS_TEXTURE);
	_add_path(GFX_DIR, BANNER_TEXTURE);
	_add_path(GFX_DIR, EVENTS_TEXTURE);
	_add_path(GFX_DIR, ICONS_TEXTURE);
	_add_path(GFX_DIR, ITEMS_TEXTURE);
	_add_path(GFX_DIR, KNOWN_CREATURES_TEXTURE);
	_add_path(GFX_DIR, LOGO_TEXTURE);
	_add_path(GFX_DIR, MAPS_TEXTURE);
	_add_path(GFX_DIR, UNKNOWN_CREATURES_TEXTURE);
	_add_path(GFX_DIR, WIREFRAME_TEXTURE);

	// Audio Files (required)
	_add_path(SFX_DIR, ENGINE_MUSIC);
	_add_path(SFX_DIR, MAINMENU_MUSIC);
	_add_path(SFX_DIR, TOWN_MUSIC);

	// Video Files (required)
	_add_path(VFX_DIR, MAINMENU_VIDEO);

	// Validate that all required files and directories exist
	_validate_files();
}

auto Sorcery::FileStore::get(const std::string_view key) const
	-> std::filesystem::path {

	const auto found{_file_paths.find(std::string{key})};

	return found != _file_paths.end() ? found->second
									  : std::filesystem::path{FILE_NOT_FOUND};
}

auto Sorcery::FileStore::get_path(const std::string_view key) const
	-> std::string {

	const auto found{_file_paths.find(std::string{key})};

	return found != _file_paths.end() ? found->second.string()
									  : std::string{FILE_NOT_FOUND};
}

auto Sorcery::FileStore::get_directory(std::string_view key) const
	-> std::filesystem::path {

	const auto found{_directory_paths.find(std::string{key})};

	return found != _directory_paths.end()
			   ? found->second
			   : std::filesystem::path{FILE_NOT_FOUND};
}

auto Sorcery::FileStore::get_directory_path(std::string_view key) const
	-> std::string {

	const auto found{_directory_paths.find(std::string{key})};

	return found != _directory_paths.end()
			   ? found->second
			   : std::filesystem::path{FILE_NOT_FOUND};
}

auto Sorcery::FileStore::get_base_path() const -> std::filesystem::path {

	return _base_path;
}

auto Sorcery::FileStore::_add_path(const std::string_view dir,
								   const std::string_view file,
								   const bool required) -> void {

	const std::filesystem::path file_path{_base_path / dir / file};

	_file_paths.insert_or_assign(std::string{file}, file_path);

	if (required)
		_required_files.emplace_back(file_path);
}

auto Sorcery::FileStore::_add_directory(const std::string_view dir,
										const std::string_view sub_dir,
										const bool required) -> void {

	const std::filesystem::path dir_path{_base_path / dir / sub_dir};
	const std::string key{std::string{sub_dir}};

	_directory_paths.insert_or_assign(std::string{key}, dir_path);

	if (required)
		_required_directories.emplace_back(dir_path);
}

auto Sorcery::FileStore::_add_directory(const std::string_view dir,
										const bool required) -> void {

	const std::filesystem::path dir_path{_base_path / dir};

	_directory_paths.insert_or_assign(std::string{dir}, dir_path);

	if (required)
		_required_directories.emplace_back(dir_path);
}

auto Sorcery::FileStore::_add_path(const std::string_view dir,
								   const std::string_view sub_dir,
								   const std::string_view file,
								   const bool required) -> void {

	const std::filesystem::path file_path{_base_path / dir / sub_dir / file};

	_file_paths.insert_or_assign(std::string{file}, file_path);

	if (required)
		_required_files.emplace_back(file_path);
}

// Validate that all required files and directories exist
auto Sorcery::FileStore::_validate_files() const -> void {

	std::vector<std::filesystem::path> missing_files;
	std::vector<std::filesystem::path> missing_directories;

	// Check for missing directories
	for (const auto &dir : _required_directories) {
		std::error_code error;

		DEBUG_LOGF("Checking required directory: {}", dir.string());

		const bool exists{std::filesystem::exists(dir, error)};
		const bool directory{exists &&
							 std::filesystem::is_directory(dir, error)};

		if (error || !directory)
			missing_directories.emplace_back(dir);
	}

	// Check for missing files
	for (const auto &file : _required_files) {
		std::error_code error;

		DEBUG_LOGF("Checking required file: {}", file.string());

		const bool exists{std::filesystem::exists(file, error)};
		const bool regular{exists &&
						   std::filesystem::is_regular_file(file, error)};

		if (error || !regular)
			missing_files.emplace_back(file);
	}

	// If any required files or directories are missing, throw an exception with
	// a detailed message
	if (missing_files.empty() && missing_directories.empty())
		return;

	std::ostringstream message;

	message << "Sorcery could not start because " << missing_files.size()
			<< " required runtime file";
	if (missing_files.size() != 1)
		message << 's';
	message << " could not be found:\n";
	for (const auto &file : missing_files)
		message << "\n  " << file.string();

	if (!missing_directories.empty()) {
		message << "\n\nAdditionally, " << missing_directories.size()
				<< " required runtime directory";
		if (missing_directories.size() != 1)
			message << 's';
		message << " could not be found:\n";

		for (const auto &dir : missing_directories)
			message << "\n  " << dir.string();
	}

	message << "\n\nExecutable directory:\n  " << _base_path.string();

	throw std::runtime_error{message.str()};
}

auto Sorcery::FileStore::_get_exe_path() const -> std::filesystem::path {

#ifdef __linux__

	std::array<char, PATH_MAX> result{};

	const ssize_t count{
		::readlink("/proc/self/exe", result.data(), result.size() - 1)};

	if (count < 0)
		return {};

	result[static_cast<std::size_t>(count)] = '\0';

	return std::filesystem::path{result.data()}.parent_path();

#elif defined(_WIN32)

	std::vector<wchar_t> buffer(MAX_PATH);

	for (;;) {
		const DWORD copied{GetModuleFileNameW(
			nullptr, buffer.data(), static_cast<DWORD>(buffer.size()))};

		if (copied == 0)
			return {};

		if (copied < buffer.size() - 1) {
			buffer.resize(copied);

			return std::filesystem::path{
				std::wstring{buffer.begin(), buffer.end()}}
				.parent_path();
		}

		buffer.resize(buffer.size() * 2);
	}

#else

#error Unsupported platform

#endif
}
