// Copyright (C) 2026 Dave Moore
//
// This file is part of Sorcery.
//
// Sorcery is free software: you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the Free Software
// Foundation, either version 2 of the License, or (at your option) any later
// version.
//
// Sorcery is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
// A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with
// Sorcery.  If not, see <http://www.gnu.org/licenses/>.
//
// If you modify this program, or any covered work, by linking or combining
// it with the libraries referred to in README (or a modified version of
// said libraries), containing parts covered by the terms of said libraries,
// the licensors of this program grant you additional permission to convey
// the resulting work.

#include "resources/filestore.hpp"
#include "common/define.hpp"
#include "resources/define.hpp"
#include <libgen.h>
#include <limits.h>
#include <unistd.h>

#include "resources/filestore.hpp"

#include "common/define.hpp"
#include "resources/define.hpp"

#include <array>
#include <sstream>
#include <stdexcept>
#include <system_error>

#ifdef __linux__
#include <limits.h>
#include <unistd.h>
#elif defined(_WIN32)
#include <windows.h>
#endif

Sorcery::FileStore::FileStore() {

	_base_path = _get_exe_path();

	if (_base_path.empty()) {
		throw std::runtime_error{
			"Unable to determine the Sorcery executable directory."};
	}

	_file_paths.clear();
	_required_files.clear();

	_add_path(CONFIG_DIR, CONFIG_FILE);

	// Generated by ImGui if it does not already exist.
	_add_path(CONFIG_DIR, IMGUI_INI_FILE, false);

	_add_path(DATA_DIR, DATABASE_FILE);
	_add_path(DATA_DIR, ITEMS_FILE);
	_add_path(DATA_DIR, LAYOUT_FILE);
	_add_path(DATA_DIR, MAPS_FILE);
	_add_path(DATA_DIR, MONOSPACE_1_APPLE2_FILE);
	_add_path(DATA_DIR, MONOSPACE_1_C64_FILE);
	_add_path(DATA_DIR, MONOSPACE_1_DOS_FILE);
	_add_path(DATA_DIR, MONOSPACE_1_MSX2_FILE);
	_add_path(DATA_DIR, MONOSPACE_5_DOS_FILE);
	_add_path(DATA_DIR, MONOSPACE_5_FMTOWNS_FILE);
	_add_path(DATA_DIR, MONSTERS_FILE);
	_add_path(DATA_DIR, PROPORTIONAL_FONT_FILE);
	_add_path(DATA_DIR, STRINGS_FILE);
	_add_path(DATA_DIR, TEXT_FONT_FILE);

	_add_path(DOCUMENTS_DIR, LICENSE_FILE);

	_add_path(GFX_DIR, BACKGROUNDS_TEXTURE);
	_add_path(GFX_DIR, BANNER_TEXTURE);
	_add_path(GFX_DIR, EVENTS_TEXTURE);
	_add_path(GFX_DIR, ICONS_TEXTURE);
	_add_path(GFX_DIR, ITEMS_TEXTURE);
	_add_path(GFX_DIR, KNOWN_CREATURES_TEXTURE);
	_add_path(GFX_DIR, LOGO_TEXTURE);
	_add_path(GFX_DIR, MAPS_TEXTURE);
	_add_path(GFX_DIR, UNKNOWN_CREATURES_TEXTURE);
	_add_path(GFX_DIR, WIREFRAME_TEXTURE);

	_add_path(SFX_DIR, ENGINE_MUSIC);
	_add_path(SFX_DIR, MAINMENU_MUSIC);
	_add_path(SFX_DIR, TOWN_MUSIC);

	_add_path(VFX_DIR, MAINMENU_VIDEO);

	_validate_files();
}

auto Sorcery::FileStore::get(const std::string_view key) const
	-> std::filesystem::path {

	const auto found{_file_paths.find(std::string{key})};

	return found != _file_paths.end() ? found->second
									  : std::filesystem::path{FILE_NOT_FOUND};
}

auto Sorcery::FileStore::get_path(const std::string_view key) const
	-> std::string {

	const auto found{_file_paths.find(std::string{key})};

	return found != _file_paths.end() ? found->second.string()
									  : std::string{FILE_NOT_FOUND};
}

auto Sorcery::FileStore::get_base_path() const -> std::filesystem::path {

	return _base_path;
}

auto Sorcery::FileStore::_add_path(const std::string_view dir,
								   const std::string_view file,
								   const bool required) -> void {

	const std::filesystem::path file_path{_base_path / dir / file};

	_file_paths.insert_or_assign(std::string{file}, file_path);

	if (required)
		_required_files.emplace_back(file_path);
}

auto Sorcery::FileStore::_validate_files() const -> void {

	std::vector<std::filesystem::path> missing_files;

	for (const auto &file : _required_files) {
		std::error_code error;

		const bool exists{std::filesystem::exists(file, error)};
		const bool regular{exists &&
						   std::filesystem::is_regular_file(file, error)};

		if (error || !regular)
			missing_files.emplace_back(file);
	}

	if (missing_files.empty())
		return;

	std::ostringstream message;

	message << "Sorcery could not start because " << missing_files.size()
			<< " required runtime file";

	if (missing_files.size() != 1)
		message << 's';

	message << " could not be found:\n";

	for (const auto &file : missing_files)
		message << "\n  " << file.string();

	message << "\n\nExecutable directory:\n  " << _base_path.string();

	throw std::runtime_error{message.str()};
}

auto Sorcery::FileStore::_get_exe_path() const -> std::filesystem::path {

#ifdef __linux__

	std::array<char, PATH_MAX> result{};

	const ssize_t count{
		::readlink("/proc/self/exe", result.data(), result.size() - 1)};

	if (count < 0)
		return {};

	result[static_cast<std::size_t>(count)] = '\0';

	return std::filesystem::path{result.data()}.parent_path();

#elif defined(_WIN32)

	std::vector<wchar_t> buffer(MAX_PATH);

	for (;;) {
		const DWORD copied{GetModuleFileNameW(
			nullptr, buffer.data(), static_cast<DWORD>(buffer.size()))};

		if (copied == 0)
			return {};

		if (copied < buffer.size() - 1) {
			buffer.resize(copied);

			return std::filesystem::path{
				std::wstring{buffer.begin(), buffer.end()}}
				.parent_path();
		}

		buffer.resize(buffer.size() * 2);
	}

#else

#error Unsupported platform

#endif
}
