# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1435/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1435/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dave/sdl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dave/sdl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/snap/cmake/1435/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/snap/cmake/1435/bin/cpack --config ./CPackSourceConfig.cmake /home/dave/sdl/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1429/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1435/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dave/sdl/CMakeFiles /home/dave/sdl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dave/sdl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dear_imgui

# Build rule for target.
dear_imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dear_imgui
.PHONY : dear_imgui

# fast build rule for target.
dear_imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/build
.PHONY : dear_imgui/fast

#=============================================================================
# Target rules for targets named sorcery

# Build rule for target.
sorcery: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sorcery
.PHONY : sorcery

# fast build rule for target.
sorcery/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/build
.PHONY : sorcery/fast

ext/imgui/backends/imgui_impl_opengl3.o: ext/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : ext/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
ext/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : ext/imgui/backends/imgui_impl_opengl3.cpp.o

ext/imgui/backends/imgui_impl_opengl3.i: ext/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : ext/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
ext/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : ext/imgui/backends/imgui_impl_opengl3.cpp.i

ext/imgui/backends/imgui_impl_opengl3.s: ext/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : ext/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
ext/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : ext/imgui/backends/imgui_impl_opengl3.cpp.s

ext/imgui/backends/imgui_impl_sdl2.o: ext/imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : ext/imgui/backends/imgui_impl_sdl2.o

# target to build an object file
ext/imgui/backends/imgui_impl_sdl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : ext/imgui/backends/imgui_impl_sdl2.cpp.o

ext/imgui/backends/imgui_impl_sdl2.i: ext/imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : ext/imgui/backends/imgui_impl_sdl2.i

# target to preprocess a source file
ext/imgui/backends/imgui_impl_sdl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : ext/imgui/backends/imgui_impl_sdl2.cpp.i

ext/imgui/backends/imgui_impl_sdl2.s: ext/imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : ext/imgui/backends/imgui_impl_sdl2.s

# target to generate assembly for a file
ext/imgui/backends/imgui_impl_sdl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : ext/imgui/backends/imgui_impl_sdl2.cpp.s

ext/imgui/imgui.o: ext/imgui/imgui.cpp.o
.PHONY : ext/imgui/imgui.o

# target to build an object file
ext/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/imgui.cpp.o
.PHONY : ext/imgui/imgui.cpp.o

ext/imgui/imgui.i: ext/imgui/imgui.cpp.i
.PHONY : ext/imgui/imgui.i

# target to preprocess a source file
ext/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/imgui.cpp.i
.PHONY : ext/imgui/imgui.cpp.i

ext/imgui/imgui.s: ext/imgui/imgui.cpp.s
.PHONY : ext/imgui/imgui.s

# target to generate assembly for a file
ext/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/imgui.cpp.s
.PHONY : ext/imgui/imgui.cpp.s

ext/imgui/imgui_demo.o: ext/imgui/imgui_demo.cpp.o
.PHONY : ext/imgui/imgui_demo.o

# target to build an object file
ext/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/imgui_demo.cpp.o
.PHONY : ext/imgui/imgui_demo.cpp.o

ext/imgui/imgui_demo.i: ext/imgui/imgui_demo.cpp.i
.PHONY : ext/imgui/imgui_demo.i

# target to preprocess a source file
ext/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/imgui_demo.cpp.i
.PHONY : ext/imgui/imgui_demo.cpp.i

ext/imgui/imgui_demo.s: ext/imgui/imgui_demo.cpp.s
.PHONY : ext/imgui/imgui_demo.s

# target to generate assembly for a file
ext/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/imgui_demo.cpp.s
.PHONY : ext/imgui/imgui_demo.cpp.s

ext/imgui/imgui_draw.o: ext/imgui/imgui_draw.cpp.o
.PHONY : ext/imgui/imgui_draw.o

# target to build an object file
ext/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/imgui_draw.cpp.o
.PHONY : ext/imgui/imgui_draw.cpp.o

ext/imgui/imgui_draw.i: ext/imgui/imgui_draw.cpp.i
.PHONY : ext/imgui/imgui_draw.i

# target to preprocess a source file
ext/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/imgui_draw.cpp.i
.PHONY : ext/imgui/imgui_draw.cpp.i

ext/imgui/imgui_draw.s: ext/imgui/imgui_draw.cpp.s
.PHONY : ext/imgui/imgui_draw.s

# target to generate assembly for a file
ext/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/imgui_draw.cpp.s
.PHONY : ext/imgui/imgui_draw.cpp.s

ext/imgui/imgui_tables.o: ext/imgui/imgui_tables.cpp.o
.PHONY : ext/imgui/imgui_tables.o

# target to build an object file
ext/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/imgui_tables.cpp.o
.PHONY : ext/imgui/imgui_tables.cpp.o

ext/imgui/imgui_tables.i: ext/imgui/imgui_tables.cpp.i
.PHONY : ext/imgui/imgui_tables.i

# target to preprocess a source file
ext/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/imgui_tables.cpp.i
.PHONY : ext/imgui/imgui_tables.cpp.i

ext/imgui/imgui_tables.s: ext/imgui/imgui_tables.cpp.s
.PHONY : ext/imgui/imgui_tables.s

# target to generate assembly for a file
ext/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/imgui_tables.cpp.s
.PHONY : ext/imgui/imgui_tables.cpp.s

ext/imgui/imgui_widgets.o: ext/imgui/imgui_widgets.cpp.o
.PHONY : ext/imgui/imgui_widgets.o

# target to build an object file
ext/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/imgui_widgets.cpp.o
.PHONY : ext/imgui/imgui_widgets.cpp.o

ext/imgui/imgui_widgets.i: ext/imgui/imgui_widgets.cpp.i
.PHONY : ext/imgui/imgui_widgets.i

# target to preprocess a source file
ext/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/imgui_widgets.cpp.i
.PHONY : ext/imgui/imgui_widgets.cpp.i

ext/imgui/imgui_widgets.s: ext/imgui/imgui_widgets.cpp.s
.PHONY : ext/imgui/imgui_widgets.s

# target to generate assembly for a file
ext/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui/imgui_widgets.cpp.s
.PHONY : ext/imgui/imgui_widgets.cpp.s

ext/imgui_toggle/imgui_toggle.o: ext/imgui_toggle/imgui_toggle.cpp.o
.PHONY : ext/imgui_toggle/imgui_toggle.o

# target to build an object file
ext/imgui_toggle/imgui_toggle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui_toggle/imgui_toggle.cpp.o
.PHONY : ext/imgui_toggle/imgui_toggle.cpp.o

ext/imgui_toggle/imgui_toggle.i: ext/imgui_toggle/imgui_toggle.cpp.i
.PHONY : ext/imgui_toggle/imgui_toggle.i

# target to preprocess a source file
ext/imgui_toggle/imgui_toggle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui_toggle/imgui_toggle.cpp.i
.PHONY : ext/imgui_toggle/imgui_toggle.cpp.i

ext/imgui_toggle/imgui_toggle.s: ext/imgui_toggle/imgui_toggle.cpp.s
.PHONY : ext/imgui_toggle/imgui_toggle.s

# target to generate assembly for a file
ext/imgui_toggle/imgui_toggle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui_toggle/imgui_toggle.cpp.s
.PHONY : ext/imgui_toggle/imgui_toggle.cpp.s

ext/imgui_toggle/imgui_toggle_palette.o: ext/imgui_toggle/imgui_toggle_palette.cpp.o
.PHONY : ext/imgui_toggle/imgui_toggle_palette.o

# target to build an object file
ext/imgui_toggle/imgui_toggle_palette.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui_toggle/imgui_toggle_palette.cpp.o
.PHONY : ext/imgui_toggle/imgui_toggle_palette.cpp.o

ext/imgui_toggle/imgui_toggle_palette.i: ext/imgui_toggle/imgui_toggle_palette.cpp.i
.PHONY : ext/imgui_toggle/imgui_toggle_palette.i

# target to preprocess a source file
ext/imgui_toggle/imgui_toggle_palette.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui_toggle/imgui_toggle_palette.cpp.i
.PHONY : ext/imgui_toggle/imgui_toggle_palette.cpp.i

ext/imgui_toggle/imgui_toggle_palette.s: ext/imgui_toggle/imgui_toggle_palette.cpp.s
.PHONY : ext/imgui_toggle/imgui_toggle_palette.s

# target to generate assembly for a file
ext/imgui_toggle/imgui_toggle_palette.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui_toggle/imgui_toggle_palette.cpp.s
.PHONY : ext/imgui_toggle/imgui_toggle_palette.cpp.s

ext/imgui_toggle/imgui_toggle_presets.o: ext/imgui_toggle/imgui_toggle_presets.cpp.o
.PHONY : ext/imgui_toggle/imgui_toggle_presets.o

# target to build an object file
ext/imgui_toggle/imgui_toggle_presets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui_toggle/imgui_toggle_presets.cpp.o
.PHONY : ext/imgui_toggle/imgui_toggle_presets.cpp.o

ext/imgui_toggle/imgui_toggle_presets.i: ext/imgui_toggle/imgui_toggle_presets.cpp.i
.PHONY : ext/imgui_toggle/imgui_toggle_presets.i

# target to preprocess a source file
ext/imgui_toggle/imgui_toggle_presets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui_toggle/imgui_toggle_presets.cpp.i
.PHONY : ext/imgui_toggle/imgui_toggle_presets.cpp.i

ext/imgui_toggle/imgui_toggle_presets.s: ext/imgui_toggle/imgui_toggle_presets.cpp.s
.PHONY : ext/imgui_toggle/imgui_toggle_presets.s

# target to generate assembly for a file
ext/imgui_toggle/imgui_toggle_presets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui_toggle/imgui_toggle_presets.cpp.s
.PHONY : ext/imgui_toggle/imgui_toggle_presets.cpp.s

ext/imgui_toggle/imgui_toggle_renderer.o: ext/imgui_toggle/imgui_toggle_renderer.cpp.o
.PHONY : ext/imgui_toggle/imgui_toggle_renderer.o

# target to build an object file
ext/imgui_toggle/imgui_toggle_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui_toggle/imgui_toggle_renderer.cpp.o
.PHONY : ext/imgui_toggle/imgui_toggle_renderer.cpp.o

ext/imgui_toggle/imgui_toggle_renderer.i: ext/imgui_toggle/imgui_toggle_renderer.cpp.i
.PHONY : ext/imgui_toggle/imgui_toggle_renderer.i

# target to preprocess a source file
ext/imgui_toggle/imgui_toggle_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui_toggle/imgui_toggle_renderer.cpp.i
.PHONY : ext/imgui_toggle/imgui_toggle_renderer.cpp.i

ext/imgui_toggle/imgui_toggle_renderer.s: ext/imgui_toggle/imgui_toggle_renderer.cpp.s
.PHONY : ext/imgui_toggle/imgui_toggle_renderer.s

# target to generate assembly for a file
ext/imgui_toggle/imgui_toggle_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dear_imgui.dir/build.make CMakeFiles/dear_imgui.dir/ext/imgui_toggle/imgui_toggle_renderer.cpp.s
.PHONY : ext/imgui_toggle/imgui_toggle_renderer.cpp.s

src/core/animation.o: src/core/animation.cpp.o
.PHONY : src/core/animation.o

# target to build an object file
src/core/animation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/animation.cpp.o
.PHONY : src/core/animation.cpp.o

src/core/animation.i: src/core/animation.cpp.i
.PHONY : src/core/animation.i

# target to preprocess a source file
src/core/animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/animation.cpp.i
.PHONY : src/core/animation.cpp.i

src/core/animation.s: src/core/animation.cpp.s
.PHONY : src/core/animation.s

# target to generate assembly for a file
src/core/animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/animation.cpp.s
.PHONY : src/core/animation.cpp.s

src/core/application.o: src/core/application.cpp.o
.PHONY : src/core/application.o

# target to build an object file
src/core/application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/application.cpp.o
.PHONY : src/core/application.cpp.o

src/core/application.i: src/core/application.cpp.i
.PHONY : src/core/application.i

# target to preprocess a source file
src/core/application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/application.cpp.i
.PHONY : src/core/application.cpp.i

src/core/application.s: src/core/application.cpp.s
.PHONY : src/core/application.s

# target to generate assembly for a file
src/core/application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/application.cpp.s
.PHONY : src/core/application.cpp.s

src/core/controller.o: src/core/controller.cpp.o
.PHONY : src/core/controller.o

# target to build an object file
src/core/controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/controller.cpp.o
.PHONY : src/core/controller.cpp.o

src/core/controller.i: src/core/controller.cpp.i
.PHONY : src/core/controller.i

# target to preprocess a source file
src/core/controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/controller.cpp.i
.PHONY : src/core/controller.cpp.i

src/core/controller.s: src/core/controller.cpp.s
.PHONY : src/core/controller.s

# target to generate assembly for a file
src/core/controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/controller.cpp.s
.PHONY : src/core/controller.cpp.s

src/core/database.o: src/core/database.cpp.o
.PHONY : src/core/database.o

# target to build an object file
src/core/database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/database.cpp.o
.PHONY : src/core/database.cpp.o

src/core/database.i: src/core/database.cpp.i
.PHONY : src/core/database.i

# target to preprocess a source file
src/core/database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/database.cpp.i
.PHONY : src/core/database.cpp.i

src/core/database.s: src/core/database.cpp.s
.PHONY : src/core/database.s

# target to generate assembly for a file
src/core/database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/database.cpp.s
.PHONY : src/core/database.cpp.s

src/core/display.o: src/core/display.cpp.o
.PHONY : src/core/display.o

# target to build an object file
src/core/display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/display.cpp.o
.PHONY : src/core/display.cpp.o

src/core/display.i: src/core/display.cpp.i
.PHONY : src/core/display.i

# target to preprocess a source file
src/core/display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/display.cpp.i
.PHONY : src/core/display.cpp.i

src/core/display.s: src/core/display.cpp.s
.PHONY : src/core/display.s

# target to generate assembly for a file
src/core/display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/display.cpp.s
.PHONY : src/core/display.cpp.s

src/core/random.o: src/core/random.cpp.o
.PHONY : src/core/random.o

# target to build an object file
src/core/random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/random.cpp.o
.PHONY : src/core/random.cpp.o

src/core/random.i: src/core/random.cpp.i
.PHONY : src/core/random.i

# target to preprocess a source file
src/core/random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/random.cpp.i
.PHONY : src/core/random.cpp.i

src/core/random.s: src/core/random.cpp.s
.PHONY : src/core/random.s

# target to generate assembly for a file
src/core/random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/random.cpp.s
.PHONY : src/core/random.cpp.s

src/core/resources.o: src/core/resources.cpp.o
.PHONY : src/core/resources.o

# target to build an object file
src/core/resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/resources.cpp.o
.PHONY : src/core/resources.cpp.o

src/core/resources.i: src/core/resources.cpp.i
.PHONY : src/core/resources.i

# target to preprocess a source file
src/core/resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/resources.cpp.i
.PHONY : src/core/resources.cpp.i

src/core/resources.s: src/core/resources.cpp.s
.PHONY : src/core/resources.s

# target to generate assembly for a file
src/core/resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/resources.cpp.s
.PHONY : src/core/resources.cpp.s

src/core/system.o: src/core/system.cpp.o
.PHONY : src/core/system.o

# target to build an object file
src/core/system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/system.cpp.o
.PHONY : src/core/system.cpp.o

src/core/system.i: src/core/system.cpp.i
.PHONY : src/core/system.i

# target to preprocess a source file
src/core/system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/system.cpp.i
.PHONY : src/core/system.cpp.i

src/core/system.s: src/core/system.cpp.s
.PHONY : src/core/system.s

# target to generate assembly for a file
src/core/system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/system.cpp.s
.PHONY : src/core/system.cpp.s

src/core/ui.o: src/core/ui.cpp.o
.PHONY : src/core/ui.o

# target to build an object file
src/core/ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/ui.cpp.o
.PHONY : src/core/ui.cpp.o

src/core/ui.i: src/core/ui.cpp.i
.PHONY : src/core/ui.i

# target to preprocess a source file
src/core/ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/ui.cpp.i
.PHONY : src/core/ui.cpp.i

src/core/ui.s: src/core/ui.cpp.s
.PHONY : src/core/ui.s

# target to generate assembly for a file
src/core/ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/core/ui.cpp.s
.PHONY : src/core/ui.cpp.s

src/ext/backward.o: src/ext/backward.cpp.o
.PHONY : src/ext/backward.o

# target to build an object file
src/ext/backward.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/ext/backward.cpp.o
.PHONY : src/ext/backward.cpp.o

src/ext/backward.i: src/ext/backward.cpp.i
.PHONY : src/ext/backward.i

# target to preprocess a source file
src/ext/backward.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/ext/backward.cpp.i
.PHONY : src/ext/backward.cpp.i

src/ext/backward.s: src/ext/backward.cpp.s
.PHONY : src/ext/backward.s

# target to generate assembly for a file
src/ext/backward.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/ext/backward.cpp.s
.PHONY : src/ext/backward.cpp.s

src/frontend/atlas.o: src/frontend/atlas.cpp.o
.PHONY : src/frontend/atlas.o

# target to build an object file
src/frontend/atlas.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/atlas.cpp.o
.PHONY : src/frontend/atlas.cpp.o

src/frontend/atlas.i: src/frontend/atlas.cpp.i
.PHONY : src/frontend/atlas.i

# target to preprocess a source file
src/frontend/atlas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/atlas.cpp.i
.PHONY : src/frontend/atlas.cpp.i

src/frontend/atlas.s: src/frontend/atlas.cpp.s
.PHONY : src/frontend/atlas.s

# target to generate assembly for a file
src/frontend/atlas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/atlas.cpp.s
.PHONY : src/frontend/atlas.cpp.s

src/frontend/bestiary.o: src/frontend/bestiary.cpp.o
.PHONY : src/frontend/bestiary.o

# target to build an object file
src/frontend/bestiary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/bestiary.cpp.o
.PHONY : src/frontend/bestiary.cpp.o

src/frontend/bestiary.i: src/frontend/bestiary.cpp.i
.PHONY : src/frontend/bestiary.i

# target to preprocess a source file
src/frontend/bestiary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/bestiary.cpp.i
.PHONY : src/frontend/bestiary.cpp.i

src/frontend/bestiary.s: src/frontend/bestiary.cpp.s
.PHONY : src/frontend/bestiary.s

# target to generate assembly for a file
src/frontend/bestiary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/bestiary.cpp.s
.PHONY : src/frontend/bestiary.cpp.s

src/frontend/compendium.o: src/frontend/compendium.cpp.o
.PHONY : src/frontend/compendium.o

# target to build an object file
src/frontend/compendium.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/compendium.cpp.o
.PHONY : src/frontend/compendium.cpp.o

src/frontend/compendium.i: src/frontend/compendium.cpp.i
.PHONY : src/frontend/compendium.i

# target to preprocess a source file
src/frontend/compendium.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/compendium.cpp.i
.PHONY : src/frontend/compendium.cpp.i

src/frontend/compendium.s: src/frontend/compendium.cpp.s
.PHONY : src/frontend/compendium.s

# target to generate assembly for a file
src/frontend/compendium.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/compendium.cpp.s
.PHONY : src/frontend/compendium.cpp.s

src/frontend/license.o: src/frontend/license.cpp.o
.PHONY : src/frontend/license.o

# target to build an object file
src/frontend/license.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/license.cpp.o
.PHONY : src/frontend/license.cpp.o

src/frontend/license.i: src/frontend/license.cpp.i
.PHONY : src/frontend/license.i

# target to preprocess a source file
src/frontend/license.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/license.cpp.i
.PHONY : src/frontend/license.cpp.i

src/frontend/license.s: src/frontend/license.cpp.s
.PHONY : src/frontend/license.s

# target to generate assembly for a file
src/frontend/license.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/license.cpp.s
.PHONY : src/frontend/license.cpp.s

src/frontend/mainmenu.o: src/frontend/mainmenu.cpp.o
.PHONY : src/frontend/mainmenu.o

# target to build an object file
src/frontend/mainmenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/mainmenu.cpp.o
.PHONY : src/frontend/mainmenu.cpp.o

src/frontend/mainmenu.i: src/frontend/mainmenu.cpp.i
.PHONY : src/frontend/mainmenu.i

# target to preprocess a source file
src/frontend/mainmenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/mainmenu.cpp.i
.PHONY : src/frontend/mainmenu.cpp.i

src/frontend/mainmenu.s: src/frontend/mainmenu.cpp.s
.PHONY : src/frontend/mainmenu.s

# target to generate assembly for a file
src/frontend/mainmenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/mainmenu.cpp.s
.PHONY : src/frontend/mainmenu.cpp.s

src/frontend/museum.o: src/frontend/museum.cpp.o
.PHONY : src/frontend/museum.o

# target to build an object file
src/frontend/museum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/museum.cpp.o
.PHONY : src/frontend/museum.cpp.o

src/frontend/museum.i: src/frontend/museum.cpp.i
.PHONY : src/frontend/museum.i

# target to preprocess a source file
src/frontend/museum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/museum.cpp.i
.PHONY : src/frontend/museum.cpp.i

src/frontend/museum.s: src/frontend/museum.cpp.s
.PHONY : src/frontend/museum.s

# target to generate assembly for a file
src/frontend/museum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/museum.cpp.s
.PHONY : src/frontend/museum.cpp.s

src/frontend/options.o: src/frontend/options.cpp.o
.PHONY : src/frontend/options.o

# target to build an object file
src/frontend/options.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/options.cpp.o
.PHONY : src/frontend/options.cpp.o

src/frontend/options.i: src/frontend/options.cpp.i
.PHONY : src/frontend/options.i

# target to preprocess a source file
src/frontend/options.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/options.cpp.i
.PHONY : src/frontend/options.cpp.i

src/frontend/options.s: src/frontend/options.cpp.s
.PHONY : src/frontend/options.s

# target to generate assembly for a file
src/frontend/options.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/options.cpp.s
.PHONY : src/frontend/options.cpp.s

src/frontend/spellbook.o: src/frontend/spellbook.cpp.o
.PHONY : src/frontend/spellbook.o

# target to build an object file
src/frontend/spellbook.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/spellbook.cpp.o
.PHONY : src/frontend/spellbook.cpp.o

src/frontend/spellbook.i: src/frontend/spellbook.cpp.i
.PHONY : src/frontend/spellbook.i

# target to preprocess a source file
src/frontend/spellbook.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/spellbook.cpp.i
.PHONY : src/frontend/spellbook.cpp.i

src/frontend/spellbook.s: src/frontend/spellbook.cpp.s
.PHONY : src/frontend/spellbook.s

# target to generate assembly for a file
src/frontend/spellbook.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/spellbook.cpp.s
.PHONY : src/frontend/spellbook.cpp.s

src/frontend/splash.o: src/frontend/splash.cpp.o
.PHONY : src/frontend/splash.o

# target to build an object file
src/frontend/splash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/splash.cpp.o
.PHONY : src/frontend/splash.cpp.o

src/frontend/splash.i: src/frontend/splash.cpp.i
.PHONY : src/frontend/splash.i

# target to preprocess a source file
src/frontend/splash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/splash.cpp.i
.PHONY : src/frontend/splash.cpp.i

src/frontend/splash.s: src/frontend/splash.cpp.s
.PHONY : src/frontend/splash.s

# target to generate assembly for a file
src/frontend/splash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frontend/splash.cpp.s
.PHONY : src/frontend/splash.cpp.s

src/gui/choice.o: src/gui/choice.cpp.o
.PHONY : src/gui/choice.o

# target to build an object file
src/gui/choice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/gui/choice.cpp.o
.PHONY : src/gui/choice.cpp.o

src/gui/choice.i: src/gui/choice.cpp.i
.PHONY : src/gui/choice.i

# target to preprocess a source file
src/gui/choice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/gui/choice.cpp.i
.PHONY : src/gui/choice.cpp.i

src/gui/choice.s: src/gui/choice.cpp.s
.PHONY : src/gui/choice.s

# target to generate assembly for a file
src/gui/choice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/gui/choice.cpp.s
.PHONY : src/gui/choice.cpp.s

src/gui/dialog.o: src/gui/dialog.cpp.o
.PHONY : src/gui/dialog.o

# target to build an object file
src/gui/dialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/gui/dialog.cpp.o
.PHONY : src/gui/dialog.cpp.o

src/gui/dialog.i: src/gui/dialog.cpp.i
.PHONY : src/gui/dialog.i

# target to preprocess a source file
src/gui/dialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/gui/dialog.cpp.i
.PHONY : src/gui/dialog.cpp.i

src/gui/dialog.s: src/gui/dialog.cpp.s
.PHONY : src/gui/dialog.s

# target to generate assembly for a file
src/gui/dialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/gui/dialog.cpp.s
.PHONY : src/gui/dialog.cpp.s

src/gui/frame.o: src/gui/frame.cpp.o
.PHONY : src/gui/frame.o

# target to build an object file
src/gui/frame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/gui/frame.cpp.o
.PHONY : src/gui/frame.cpp.o

src/gui/frame.i: src/gui/frame.cpp.i
.PHONY : src/gui/frame.i

# target to preprocess a source file
src/gui/frame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/gui/frame.cpp.i
.PHONY : src/gui/frame.cpp.i

src/gui/frame.s: src/gui/frame.cpp.s
.PHONY : src/gui/frame.s

# target to generate assembly for a file
src/gui/frame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/gui/frame.cpp.s
.PHONY : src/gui/frame.cpp.s

src/gui/menu.o: src/gui/menu.cpp.o
.PHONY : src/gui/menu.o

# target to build an object file
src/gui/menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/gui/menu.cpp.o
.PHONY : src/gui/menu.cpp.o

src/gui/menu.i: src/gui/menu.cpp.i
.PHONY : src/gui/menu.i

# target to preprocess a source file
src/gui/menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/gui/menu.cpp.i
.PHONY : src/gui/menu.cpp.i

src/gui/menu.s: src/gui/menu.cpp.s
.PHONY : src/gui/menu.s

# target to generate assembly for a file
src/gui/menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/gui/menu.cpp.s
.PHONY : src/gui/menu.cpp.s

src/modules/add.o: src/modules/add.cpp.o
.PHONY : src/modules/add.o

# target to build an object file
src/modules/add.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/add.cpp.o
.PHONY : src/modules/add.cpp.o

src/modules/add.i: src/modules/add.cpp.i
.PHONY : src/modules/add.i

# target to preprocess a source file
src/modules/add.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/add.cpp.i
.PHONY : src/modules/add.cpp.i

src/modules/add.s: src/modules/add.cpp.s
.PHONY : src/modules/add.s

# target to generate assembly for a file
src/modules/add.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/add.cpp.s
.PHONY : src/modules/add.cpp.s

src/modules/castle.o: src/modules/castle.cpp.o
.PHONY : src/modules/castle.o

# target to build an object file
src/modules/castle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/castle.cpp.o
.PHONY : src/modules/castle.cpp.o

src/modules/castle.i: src/modules/castle.cpp.i
.PHONY : src/modules/castle.i

# target to preprocess a source file
src/modules/castle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/castle.cpp.i
.PHONY : src/modules/castle.cpp.i

src/modules/castle.s: src/modules/castle.cpp.s
.PHONY : src/modules/castle.s

# target to generate assembly for a file
src/modules/castle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/castle.cpp.s
.PHONY : src/modules/castle.cpp.s

src/modules/edgeoftown.o: src/modules/edgeoftown.cpp.o
.PHONY : src/modules/edgeoftown.o

# target to build an object file
src/modules/edgeoftown.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/edgeoftown.cpp.o
.PHONY : src/modules/edgeoftown.cpp.o

src/modules/edgeoftown.i: src/modules/edgeoftown.cpp.i
.PHONY : src/modules/edgeoftown.i

# target to preprocess a source file
src/modules/edgeoftown.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/edgeoftown.cpp.i
.PHONY : src/modules/edgeoftown.cpp.i

src/modules/edgeoftown.s: src/modules/edgeoftown.cpp.s
.PHONY : src/modules/edgeoftown.s

# target to generate assembly for a file
src/modules/edgeoftown.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/edgeoftown.cpp.s
.PHONY : src/modules/edgeoftown.cpp.s

src/modules/inn.o: src/modules/inn.cpp.o
.PHONY : src/modules/inn.o

# target to build an object file
src/modules/inn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/inn.cpp.o
.PHONY : src/modules/inn.cpp.o

src/modules/inn.i: src/modules/inn.cpp.i
.PHONY : src/modules/inn.i

# target to preprocess a source file
src/modules/inn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/inn.cpp.i
.PHONY : src/modules/inn.cpp.i

src/modules/inn.s: src/modules/inn.cpp.s
.PHONY : src/modules/inn.s

# target to generate assembly for a file
src/modules/inn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/inn.cpp.s
.PHONY : src/modules/inn.cpp.s

src/modules/remove.o: src/modules/remove.cpp.o
.PHONY : src/modules/remove.o

# target to build an object file
src/modules/remove.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/remove.cpp.o
.PHONY : src/modules/remove.cpp.o

src/modules/remove.i: src/modules/remove.cpp.i
.PHONY : src/modules/remove.i

# target to preprocess a source file
src/modules/remove.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/remove.cpp.i
.PHONY : src/modules/remove.cpp.i

src/modules/remove.s: src/modules/remove.cpp.s
.PHONY : src/modules/remove.s

# target to generate assembly for a file
src/modules/remove.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/remove.cpp.s
.PHONY : src/modules/remove.cpp.s

src/modules/roster.o: src/modules/roster.cpp.o
.PHONY : src/modules/roster.o

# target to build an object file
src/modules/roster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/roster.cpp.o
.PHONY : src/modules/roster.cpp.o

src/modules/roster.i: src/modules/roster.cpp.i
.PHONY : src/modules/roster.i

# target to preprocess a source file
src/modules/roster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/roster.cpp.i
.PHONY : src/modules/roster.cpp.i

src/modules/roster.s: src/modules/roster.cpp.s
.PHONY : src/modules/roster.s

# target to generate assembly for a file
src/modules/roster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/roster.cpp.s
.PHONY : src/modules/roster.cpp.s

src/modules/shop.o: src/modules/shop.cpp.o
.PHONY : src/modules/shop.o

# target to build an object file
src/modules/shop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/shop.cpp.o
.PHONY : src/modules/shop.cpp.o

src/modules/shop.i: src/modules/shop.cpp.i
.PHONY : src/modules/shop.i

# target to preprocess a source file
src/modules/shop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/shop.cpp.i
.PHONY : src/modules/shop.cpp.i

src/modules/shop.s: src/modules/shop.cpp.s
.PHONY : src/modules/shop.s

# target to generate assembly for a file
src/modules/shop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/shop.cpp.s
.PHONY : src/modules/shop.cpp.s

src/modules/tavern.o: src/modules/tavern.cpp.o
.PHONY : src/modules/tavern.o

# target to build an object file
src/modules/tavern.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/tavern.cpp.o
.PHONY : src/modules/tavern.cpp.o

src/modules/tavern.i: src/modules/tavern.cpp.i
.PHONY : src/modules/tavern.i

# target to preprocess a source file
src/modules/tavern.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/tavern.cpp.i
.PHONY : src/modules/tavern.cpp.i

src/modules/tavern.s: src/modules/tavern.cpp.s
.PHONY : src/modules/tavern.s

# target to generate assembly for a file
src/modules/tavern.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/tavern.cpp.s
.PHONY : src/modules/tavern.cpp.s

src/modules/temple.o: src/modules/temple.cpp.o
.PHONY : src/modules/temple.o

# target to build an object file
src/modules/temple.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/temple.cpp.o
.PHONY : src/modules/temple.cpp.o

src/modules/temple.i: src/modules/temple.cpp.i
.PHONY : src/modules/temple.i

# target to preprocess a source file
src/modules/temple.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/temple.cpp.i
.PHONY : src/modules/temple.cpp.i

src/modules/temple.s: src/modules/temple.cpp.s
.PHONY : src/modules/temple.s

# target to generate assembly for a file
src/modules/temple.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/temple.cpp.s
.PHONY : src/modules/temple.cpp.s

src/modules/training.o: src/modules/training.cpp.o
.PHONY : src/modules/training.o

# target to build an object file
src/modules/training.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/training.cpp.o
.PHONY : src/modules/training.cpp.o

src/modules/training.i: src/modules/training.cpp.i
.PHONY : src/modules/training.i

# target to preprocess a source file
src/modules/training.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/training.cpp.i
.PHONY : src/modules/training.cpp.i

src/modules/training.s: src/modules/training.cpp.s
.PHONY : src/modules/training.s

# target to generate assembly for a file
src/modules/training.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/modules/training.cpp.s
.PHONY : src/modules/training.cpp.s

src/resources/componentstore.o: src/resources/componentstore.cpp.o
.PHONY : src/resources/componentstore.o

# target to build an object file
src/resources/componentstore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/componentstore.cpp.o
.PHONY : src/resources/componentstore.cpp.o

src/resources/componentstore.i: src/resources/componentstore.cpp.i
.PHONY : src/resources/componentstore.i

# target to preprocess a source file
src/resources/componentstore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/componentstore.cpp.i
.PHONY : src/resources/componentstore.cpp.i

src/resources/componentstore.s: src/resources/componentstore.cpp.s
.PHONY : src/resources/componentstore.s

# target to generate assembly for a file
src/resources/componentstore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/componentstore.cpp.s
.PHONY : src/resources/componentstore.cpp.s

src/resources/filestore.o: src/resources/filestore.cpp.o
.PHONY : src/resources/filestore.o

# target to build an object file
src/resources/filestore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/filestore.cpp.o
.PHONY : src/resources/filestore.cpp.o

src/resources/filestore.i: src/resources/filestore.cpp.i
.PHONY : src/resources/filestore.i

# target to preprocess a source file
src/resources/filestore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/filestore.cpp.i
.PHONY : src/resources/filestore.cpp.i

src/resources/filestore.s: src/resources/filestore.cpp.s
.PHONY : src/resources/filestore.s

# target to generate assembly for a file
src/resources/filestore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/filestore.cpp.s
.PHONY : src/resources/filestore.cpp.s

src/resources/imagestore.o: src/resources/imagestore.cpp.o
.PHONY : src/resources/imagestore.o

# target to build an object file
src/resources/imagestore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/imagestore.cpp.o
.PHONY : src/resources/imagestore.cpp.o

src/resources/imagestore.i: src/resources/imagestore.cpp.i
.PHONY : src/resources/imagestore.i

# target to preprocess a source file
src/resources/imagestore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/imagestore.cpp.i
.PHONY : src/resources/imagestore.cpp.i

src/resources/imagestore.s: src/resources/imagestore.cpp.s
.PHONY : src/resources/imagestore.s

# target to generate assembly for a file
src/resources/imagestore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/imagestore.cpp.s
.PHONY : src/resources/imagestore.cpp.s

src/resources/itemstore.o: src/resources/itemstore.cpp.o
.PHONY : src/resources/itemstore.o

# target to build an object file
src/resources/itemstore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/itemstore.cpp.o
.PHONY : src/resources/itemstore.cpp.o

src/resources/itemstore.i: src/resources/itemstore.cpp.i
.PHONY : src/resources/itemstore.i

# target to preprocess a source file
src/resources/itemstore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/itemstore.cpp.i
.PHONY : src/resources/itemstore.cpp.i

src/resources/itemstore.s: src/resources/itemstore.cpp.s
.PHONY : src/resources/itemstore.s

# target to generate assembly for a file
src/resources/itemstore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/itemstore.cpp.s
.PHONY : src/resources/itemstore.cpp.s

src/resources/levelstore.o: src/resources/levelstore.cpp.o
.PHONY : src/resources/levelstore.o

# target to build an object file
src/resources/levelstore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/levelstore.cpp.o
.PHONY : src/resources/levelstore.cpp.o

src/resources/levelstore.i: src/resources/levelstore.cpp.i
.PHONY : src/resources/levelstore.i

# target to preprocess a source file
src/resources/levelstore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/levelstore.cpp.i
.PHONY : src/resources/levelstore.cpp.i

src/resources/levelstore.s: src/resources/levelstore.cpp.s
.PHONY : src/resources/levelstore.s

# target to generate assembly for a file
src/resources/levelstore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/levelstore.cpp.s
.PHONY : src/resources/levelstore.cpp.s

src/resources/monsterstore.o: src/resources/monsterstore.cpp.o
.PHONY : src/resources/monsterstore.o

# target to build an object file
src/resources/monsterstore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/monsterstore.cpp.o
.PHONY : src/resources/monsterstore.cpp.o

src/resources/monsterstore.i: src/resources/monsterstore.cpp.i
.PHONY : src/resources/monsterstore.i

# target to preprocess a source file
src/resources/monsterstore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/monsterstore.cpp.i
.PHONY : src/resources/monsterstore.cpp.i

src/resources/monsterstore.s: src/resources/monsterstore.cpp.s
.PHONY : src/resources/monsterstore.s

# target to generate assembly for a file
src/resources/monsterstore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/monsterstore.cpp.s
.PHONY : src/resources/monsterstore.cpp.s

src/resources/spellstore.o: src/resources/spellstore.cpp.o
.PHONY : src/resources/spellstore.o

# target to build an object file
src/resources/spellstore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/spellstore.cpp.o
.PHONY : src/resources/spellstore.cpp.o

src/resources/spellstore.i: src/resources/spellstore.cpp.i
.PHONY : src/resources/spellstore.i

# target to preprocess a source file
src/resources/spellstore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/spellstore.cpp.i
.PHONY : src/resources/spellstore.cpp.i

src/resources/spellstore.s: src/resources/spellstore.cpp.s
.PHONY : src/resources/spellstore.s

# target to generate assembly for a file
src/resources/spellstore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/spellstore.cpp.s
.PHONY : src/resources/spellstore.cpp.s

src/resources/stringstore.o: src/resources/stringstore.cpp.o
.PHONY : src/resources/stringstore.o

# target to build an object file
src/resources/stringstore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/stringstore.cpp.o
.PHONY : src/resources/stringstore.cpp.o

src/resources/stringstore.i: src/resources/stringstore.cpp.i
.PHONY : src/resources/stringstore.i

# target to preprocess a source file
src/resources/stringstore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/stringstore.cpp.i
.PHONY : src/resources/stringstore.cpp.i

src/resources/stringstore.s: src/resources/stringstore.cpp.s
.PHONY : src/resources/stringstore.s

# target to generate assembly for a file
src/resources/stringstore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resources/stringstore.cpp.s
.PHONY : src/resources/stringstore.cpp.s

src/sorcery.o: src/sorcery.cpp.o
.PHONY : src/sorcery.o

# target to build an object file
src/sorcery.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/sorcery.cpp.o
.PHONY : src/sorcery.cpp.o

src/sorcery.i: src/sorcery.cpp.i
.PHONY : src/sorcery.i

# target to preprocess a source file
src/sorcery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/sorcery.cpp.i
.PHONY : src/sorcery.cpp.i

src/sorcery.s: src/sorcery.cpp.s
.PHONY : src/sorcery.s

# target to generate assembly for a file
src/sorcery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/sorcery.cpp.s
.PHONY : src/sorcery.cpp.s

src/types/character.o: src/types/character.cpp.o
.PHONY : src/types/character.o

# target to build an object file
src/types/character.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/character.cpp.o
.PHONY : src/types/character.cpp.o

src/types/character.i: src/types/character.cpp.i
.PHONY : src/types/character.i

# target to preprocess a source file
src/types/character.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/character.cpp.i
.PHONY : src/types/character.cpp.i

src/types/character.s: src/types/character.cpp.s
.PHONY : src/types/character.s

# target to generate assembly for a file
src/types/character.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/character.cpp.s
.PHONY : src/types/character.cpp.s

src/types/component.o: src/types/component.cpp.o
.PHONY : src/types/component.o

# target to build an object file
src/types/component.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/component.cpp.o
.PHONY : src/types/component.cpp.o

src/types/component.i: src/types/component.cpp.i
.PHONY : src/types/component.i

# target to preprocess a source file
src/types/component.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/component.cpp.i
.PHONY : src/types/component.cpp.i

src/types/component.s: src/types/component.cpp.s
.PHONY : src/types/component.s

# target to generate assembly for a file
src/types/component.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/component.cpp.s
.PHONY : src/types/component.cpp.s

src/types/config.o: src/types/config.cpp.o
.PHONY : src/types/config.o

# target to build an object file
src/types/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/config.cpp.o
.PHONY : src/types/config.cpp.o

src/types/config.i: src/types/config.cpp.i
.PHONY : src/types/config.i

# target to preprocess a source file
src/types/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/config.cpp.i
.PHONY : src/types/config.cpp.i

src/types/config.s: src/types/config.cpp.s
.PHONY : src/types/config.s

# target to generate assembly for a file
src/types/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/config.cpp.s
.PHONY : src/types/config.cpp.s

src/types/dice.o: src/types/dice.cpp.o
.PHONY : src/types/dice.o

# target to build an object file
src/types/dice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/dice.cpp.o
.PHONY : src/types/dice.cpp.o

src/types/dice.i: src/types/dice.cpp.i
.PHONY : src/types/dice.i

# target to preprocess a source file
src/types/dice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/dice.cpp.i
.PHONY : src/types/dice.cpp.i

src/types/dice.s: src/types/dice.cpp.s
.PHONY : src/types/dice.s

# target to generate assembly for a file
src/types/dice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/dice.cpp.s
.PHONY : src/types/dice.cpp.s

src/types/error.o: src/types/error.cpp.o
.PHONY : src/types/error.o

# target to build an object file
src/types/error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/error.cpp.o
.PHONY : src/types/error.cpp.o

src/types/error.i: src/types/error.cpp.i
.PHONY : src/types/error.i

# target to preprocess a source file
src/types/error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/error.cpp.i
.PHONY : src/types/error.cpp.i

src/types/error.s: src/types/error.cpp.s
.PHONY : src/types/error.s

# target to generate assembly for a file
src/types/error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/error.cpp.s
.PHONY : src/types/error.cpp.s

src/types/explore.o: src/types/explore.cpp.o
.PHONY : src/types/explore.o

# target to build an object file
src/types/explore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/explore.cpp.o
.PHONY : src/types/explore.cpp.o

src/types/explore.i: src/types/explore.cpp.i
.PHONY : src/types/explore.i

# target to preprocess a source file
src/types/explore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/explore.cpp.i
.PHONY : src/types/explore.cpp.i

src/types/explore.s: src/types/explore.cpp.s
.PHONY : src/types/explore.s

# target to generate assembly for a file
src/types/explore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/explore.cpp.s
.PHONY : src/types/explore.cpp.s

src/types/game.o: src/types/game.cpp.o
.PHONY : src/types/game.o

# target to build an object file
src/types/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/game.cpp.o
.PHONY : src/types/game.cpp.o

src/types/game.i: src/types/game.cpp.i
.PHONY : src/types/game.i

# target to preprocess a source file
src/types/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/game.cpp.i
.PHONY : src/types/game.cpp.i

src/types/game.s: src/types/game.cpp.s
.PHONY : src/types/game.s

# target to generate assembly for a file
src/types/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/game.cpp.s
.PHONY : src/types/game.cpp.s

src/types/image.o: src/types/image.cpp.o
.PHONY : src/types/image.o

# target to build an object file
src/types/image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/image.cpp.o
.PHONY : src/types/image.cpp.o

src/types/image.i: src/types/image.cpp.i
.PHONY : src/types/image.i

# target to preprocess a source file
src/types/image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/image.cpp.i
.PHONY : src/types/image.cpp.i

src/types/image.s: src/types/image.cpp.s
.PHONY : src/types/image.s

# target to generate assembly for a file
src/types/image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/image.cpp.s
.PHONY : src/types/image.cpp.s

src/types/inventory.o: src/types/inventory.cpp.o
.PHONY : src/types/inventory.o

# target to build an object file
src/types/inventory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/inventory.cpp.o
.PHONY : src/types/inventory.cpp.o

src/types/inventory.i: src/types/inventory.cpp.i
.PHONY : src/types/inventory.i

# target to preprocess a source file
src/types/inventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/inventory.cpp.i
.PHONY : src/types/inventory.cpp.i

src/types/inventory.s: src/types/inventory.cpp.s
.PHONY : src/types/inventory.s

# target to generate assembly for a file
src/types/inventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/inventory.cpp.s
.PHONY : src/types/inventory.cpp.s

src/types/item.o: src/types/item.cpp.o
.PHONY : src/types/item.o

# target to build an object file
src/types/item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/item.cpp.o
.PHONY : src/types/item.cpp.o

src/types/item.i: src/types/item.cpp.i
.PHONY : src/types/item.i

# target to preprocess a source file
src/types/item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/item.cpp.i
.PHONY : src/types/item.cpp.i

src/types/item.s: src/types/item.cpp.s
.PHONY : src/types/item.s

# target to generate assembly for a file
src/types/item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/item.cpp.s
.PHONY : src/types/item.cpp.s

src/types/itemtype.o: src/types/itemtype.cpp.o
.PHONY : src/types/itemtype.o

# target to build an object file
src/types/itemtype.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/itemtype.cpp.o
.PHONY : src/types/itemtype.cpp.o

src/types/itemtype.i: src/types/itemtype.cpp.i
.PHONY : src/types/itemtype.i

# target to preprocess a source file
src/types/itemtype.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/itemtype.cpp.i
.PHONY : src/types/itemtype.cpp.i

src/types/itemtype.s: src/types/itemtype.cpp.s
.PHONY : src/types/itemtype.s

# target to generate assembly for a file
src/types/itemtype.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/itemtype.cpp.s
.PHONY : src/types/itemtype.cpp.s

src/types/level.o: src/types/level.cpp.o
.PHONY : src/types/level.o

# target to build an object file
src/types/level.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/level.cpp.o
.PHONY : src/types/level.cpp.o

src/types/level.i: src/types/level.cpp.i
.PHONY : src/types/level.i

# target to preprocess a source file
src/types/level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/level.cpp.i
.PHONY : src/types/level.cpp.i

src/types/level.s: src/types/level.cpp.s
.PHONY : src/types/level.s

# target to generate assembly for a file
src/types/level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/level.cpp.s
.PHONY : src/types/level.cpp.s

src/types/monster.o: src/types/monster.cpp.o
.PHONY : src/types/monster.o

# target to build an object file
src/types/monster.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/monster.cpp.o
.PHONY : src/types/monster.cpp.o

src/types/monster.i: src/types/monster.cpp.i
.PHONY : src/types/monster.i

# target to preprocess a source file
src/types/monster.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/monster.cpp.i
.PHONY : src/types/monster.cpp.i

src/types/monster.s: src/types/monster.cpp.s
.PHONY : src/types/monster.s

# target to generate assembly for a file
src/types/monster.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/monster.cpp.s
.PHONY : src/types/monster.cpp.s

src/types/monstertype.o: src/types/monstertype.cpp.o
.PHONY : src/types/monstertype.o

# target to build an object file
src/types/monstertype.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/monstertype.cpp.o
.PHONY : src/types/monstertype.cpp.o

src/types/monstertype.i: src/types/monstertype.cpp.i
.PHONY : src/types/monstertype.i

# target to preprocess a source file
src/types/monstertype.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/monstertype.cpp.i
.PHONY : src/types/monstertype.cpp.i

src/types/monstertype.s: src/types/monstertype.cpp.s
.PHONY : src/types/monstertype.s

# target to generate assembly for a file
src/types/monstertype.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/monstertype.cpp.s
.PHONY : src/types/monstertype.cpp.s

src/types/state.o: src/types/state.cpp.o
.PHONY : src/types/state.o

# target to build an object file
src/types/state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/state.cpp.o
.PHONY : src/types/state.cpp.o

src/types/state.i: src/types/state.cpp.i
.PHONY : src/types/state.i

# target to preprocess a source file
src/types/state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/state.cpp.i
.PHONY : src/types/state.cpp.i

src/types/state.s: src/types/state.cpp.s
.PHONY : src/types/state.s

# target to generate assembly for a file
src/types/state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/state.cpp.s
.PHONY : src/types/state.cpp.s

src/types/tile.o: src/types/tile.cpp.o
.PHONY : src/types/tile.o

# target to build an object file
src/types/tile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/tile.cpp.o
.PHONY : src/types/tile.cpp.o

src/types/tile.i: src/types/tile.cpp.i
.PHONY : src/types/tile.i

# target to preprocess a source file
src/types/tile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/tile.cpp.i
.PHONY : src/types/tile.cpp.i

src/types/tile.s: src/types/tile.cpp.s
.PHONY : src/types/tile.s

# target to generate assembly for a file
src/types/tile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/types/tile.cpp.s
.PHONY : src/types/tile.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... dear_imgui"
	@echo "... sorcery"
	@echo "... ext/imgui/backends/imgui_impl_opengl3.o"
	@echo "... ext/imgui/backends/imgui_impl_opengl3.i"
	@echo "... ext/imgui/backends/imgui_impl_opengl3.s"
	@echo "... ext/imgui/backends/imgui_impl_sdl2.o"
	@echo "... ext/imgui/backends/imgui_impl_sdl2.i"
	@echo "... ext/imgui/backends/imgui_impl_sdl2.s"
	@echo "... ext/imgui/imgui.o"
	@echo "... ext/imgui/imgui.i"
	@echo "... ext/imgui/imgui.s"
	@echo "... ext/imgui/imgui_demo.o"
	@echo "... ext/imgui/imgui_demo.i"
	@echo "... ext/imgui/imgui_demo.s"
	@echo "... ext/imgui/imgui_draw.o"
	@echo "... ext/imgui/imgui_draw.i"
	@echo "... ext/imgui/imgui_draw.s"
	@echo "... ext/imgui/imgui_tables.o"
	@echo "... ext/imgui/imgui_tables.i"
	@echo "... ext/imgui/imgui_tables.s"
	@echo "... ext/imgui/imgui_widgets.o"
	@echo "... ext/imgui/imgui_widgets.i"
	@echo "... ext/imgui/imgui_widgets.s"
	@echo "... ext/imgui_toggle/imgui_toggle.o"
	@echo "... ext/imgui_toggle/imgui_toggle.i"
	@echo "... ext/imgui_toggle/imgui_toggle.s"
	@echo "... ext/imgui_toggle/imgui_toggle_palette.o"
	@echo "... ext/imgui_toggle/imgui_toggle_palette.i"
	@echo "... ext/imgui_toggle/imgui_toggle_palette.s"
	@echo "... ext/imgui_toggle/imgui_toggle_presets.o"
	@echo "... ext/imgui_toggle/imgui_toggle_presets.i"
	@echo "... ext/imgui_toggle/imgui_toggle_presets.s"
	@echo "... ext/imgui_toggle/imgui_toggle_renderer.o"
	@echo "... ext/imgui_toggle/imgui_toggle_renderer.i"
	@echo "... ext/imgui_toggle/imgui_toggle_renderer.s"
	@echo "... src/core/animation.o"
	@echo "... src/core/animation.i"
	@echo "... src/core/animation.s"
	@echo "... src/core/application.o"
	@echo "... src/core/application.i"
	@echo "... src/core/application.s"
	@echo "... src/core/controller.o"
	@echo "... src/core/controller.i"
	@echo "... src/core/controller.s"
	@echo "... src/core/database.o"
	@echo "... src/core/database.i"
	@echo "... src/core/database.s"
	@echo "... src/core/display.o"
	@echo "... src/core/display.i"
	@echo "... src/core/display.s"
	@echo "... src/core/random.o"
	@echo "... src/core/random.i"
	@echo "... src/core/random.s"
	@echo "... src/core/resources.o"
	@echo "... src/core/resources.i"
	@echo "... src/core/resources.s"
	@echo "... src/core/system.o"
	@echo "... src/core/system.i"
	@echo "... src/core/system.s"
	@echo "... src/core/ui.o"
	@echo "... src/core/ui.i"
	@echo "... src/core/ui.s"
	@echo "... src/ext/backward.o"
	@echo "... src/ext/backward.i"
	@echo "... src/ext/backward.s"
	@echo "... src/frontend/atlas.o"
	@echo "... src/frontend/atlas.i"
	@echo "... src/frontend/atlas.s"
	@echo "... src/frontend/bestiary.o"
	@echo "... src/frontend/bestiary.i"
	@echo "... src/frontend/bestiary.s"
	@echo "... src/frontend/compendium.o"
	@echo "... src/frontend/compendium.i"
	@echo "... src/frontend/compendium.s"
	@echo "... src/frontend/license.o"
	@echo "... src/frontend/license.i"
	@echo "... src/frontend/license.s"
	@echo "... src/frontend/mainmenu.o"
	@echo "... src/frontend/mainmenu.i"
	@echo "... src/frontend/mainmenu.s"
	@echo "... src/frontend/museum.o"
	@echo "... src/frontend/museum.i"
	@echo "... src/frontend/museum.s"
	@echo "... src/frontend/options.o"
	@echo "... src/frontend/options.i"
	@echo "... src/frontend/options.s"
	@echo "... src/frontend/spellbook.o"
	@echo "... src/frontend/spellbook.i"
	@echo "... src/frontend/spellbook.s"
	@echo "... src/frontend/splash.o"
	@echo "... src/frontend/splash.i"
	@echo "... src/frontend/splash.s"
	@echo "... src/gui/choice.o"
	@echo "... src/gui/choice.i"
	@echo "... src/gui/choice.s"
	@echo "... src/gui/dialog.o"
	@echo "... src/gui/dialog.i"
	@echo "... src/gui/dialog.s"
	@echo "... src/gui/frame.o"
	@echo "... src/gui/frame.i"
	@echo "... src/gui/frame.s"
	@echo "... src/gui/menu.o"
	@echo "... src/gui/menu.i"
	@echo "... src/gui/menu.s"
	@echo "... src/modules/add.o"
	@echo "... src/modules/add.i"
	@echo "... src/modules/add.s"
	@echo "... src/modules/castle.o"
	@echo "... src/modules/castle.i"
	@echo "... src/modules/castle.s"
	@echo "... src/modules/edgeoftown.o"
	@echo "... src/modules/edgeoftown.i"
	@echo "... src/modules/edgeoftown.s"
	@echo "... src/modules/inn.o"
	@echo "... src/modules/inn.i"
	@echo "... src/modules/inn.s"
	@echo "... src/modules/remove.o"
	@echo "... src/modules/remove.i"
	@echo "... src/modules/remove.s"
	@echo "... src/modules/roster.o"
	@echo "... src/modules/roster.i"
	@echo "... src/modules/roster.s"
	@echo "... src/modules/shop.o"
	@echo "... src/modules/shop.i"
	@echo "... src/modules/shop.s"
	@echo "... src/modules/tavern.o"
	@echo "... src/modules/tavern.i"
	@echo "... src/modules/tavern.s"
	@echo "... src/modules/temple.o"
	@echo "... src/modules/temple.i"
	@echo "... src/modules/temple.s"
	@echo "... src/modules/training.o"
	@echo "... src/modules/training.i"
	@echo "... src/modules/training.s"
	@echo "... src/resources/componentstore.o"
	@echo "... src/resources/componentstore.i"
	@echo "... src/resources/componentstore.s"
	@echo "... src/resources/filestore.o"
	@echo "... src/resources/filestore.i"
	@echo "... src/resources/filestore.s"
	@echo "... src/resources/imagestore.o"
	@echo "... src/resources/imagestore.i"
	@echo "... src/resources/imagestore.s"
	@echo "... src/resources/itemstore.o"
	@echo "... src/resources/itemstore.i"
	@echo "... src/resources/itemstore.s"
	@echo "... src/resources/levelstore.o"
	@echo "... src/resources/levelstore.i"
	@echo "... src/resources/levelstore.s"
	@echo "... src/resources/monsterstore.o"
	@echo "... src/resources/monsterstore.i"
	@echo "... src/resources/monsterstore.s"
	@echo "... src/resources/spellstore.o"
	@echo "... src/resources/spellstore.i"
	@echo "... src/resources/spellstore.s"
	@echo "... src/resources/stringstore.o"
	@echo "... src/resources/stringstore.i"
	@echo "... src/resources/stringstore.s"
	@echo "... src/sorcery.o"
	@echo "... src/sorcery.i"
	@echo "... src/sorcery.s"
	@echo "... src/types/character.o"
	@echo "... src/types/character.i"
	@echo "... src/types/character.s"
	@echo "... src/types/component.o"
	@echo "... src/types/component.i"
	@echo "... src/types/component.s"
	@echo "... src/types/config.o"
	@echo "... src/types/config.i"
	@echo "... src/types/config.s"
	@echo "... src/types/dice.o"
	@echo "... src/types/dice.i"
	@echo "... src/types/dice.s"
	@echo "... src/types/error.o"
	@echo "... src/types/error.i"
	@echo "... src/types/error.s"
	@echo "... src/types/explore.o"
	@echo "... src/types/explore.i"
	@echo "... src/types/explore.s"
	@echo "... src/types/game.o"
	@echo "... src/types/game.i"
	@echo "... src/types/game.s"
	@echo "... src/types/image.o"
	@echo "... src/types/image.i"
	@echo "... src/types/image.s"
	@echo "... src/types/inventory.o"
	@echo "... src/types/inventory.i"
	@echo "... src/types/inventory.s"
	@echo "... src/types/item.o"
	@echo "... src/types/item.i"
	@echo "... src/types/item.s"
	@echo "... src/types/itemtype.o"
	@echo "... src/types/itemtype.i"
	@echo "... src/types/itemtype.s"
	@echo "... src/types/level.o"
	@echo "... src/types/level.i"
	@echo "... src/types/level.s"
	@echo "... src/types/monster.o"
	@echo "... src/types/monster.i"
	@echo "... src/types/monster.s"
	@echo "... src/types/monstertype.o"
	@echo "... src/types/monstertype.i"
	@echo "... src/types/monstertype.s"
	@echo "... src/types/state.o"
	@echo "... src/types/state.i"
	@echo "... src/types/state.s"
	@echo "... src/types/tile.o"
	@echo "... src/types/tile.i"
	@echo "... src/types/tile.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

