# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dave/Development/wizardry/sorcery-sfml

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dave/Development/wizardry/sorcery-sfml

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/dave/Development/wizardry/sorcery-sfml/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dave/Development/wizardry/sorcery-sfml/CMakeFiles /home/dave/Development/wizardry/sorcery-sfml/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dave/Development/wizardry/sorcery-sfml/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sorcery

# Build rule for target.
sorcery: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sorcery
.PHONY : sorcery

# fast build rule for target.
sorcery/fast:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/build
.PHONY : sorcery/fast

src/allocatepanel.o: src/allocatepanel.cpp.o

.PHONY : src/allocatepanel.o

# target to build an object file
src/allocatepanel.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/allocatepanel.cpp.o
.PHONY : src/allocatepanel.cpp.o

src/allocatepanel.i: src/allocatepanel.cpp.i

.PHONY : src/allocatepanel.i

# target to preprocess a source file
src/allocatepanel.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/allocatepanel.cpp.i
.PHONY : src/allocatepanel.cpp.i

src/allocatepanel.s: src/allocatepanel.cpp.s

.PHONY : src/allocatepanel.s

# target to generate assembly for a file
src/allocatepanel.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/allocatepanel.cpp.s
.PHONY : src/allocatepanel.cpp.s

src/animation.o: src/animation.cpp.o

.PHONY : src/animation.o

# target to build an object file
src/animation.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/animation.cpp.o
.PHONY : src/animation.cpp.o

src/animation.i: src/animation.cpp.i

.PHONY : src/animation.i

# target to preprocess a source file
src/animation.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/animation.cpp.i
.PHONY : src/animation.cpp.i

src/animation.s: src/animation.cpp.s

.PHONY : src/animation.s

# target to generate assembly for a file
src/animation.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/animation.cpp.s
.PHONY : src/animation.cpp.s

src/application.o: src/application.cpp.o

.PHONY : src/application.o

# target to build an object file
src/application.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/application.cpp.o
.PHONY : src/application.cpp.o

src/application.i: src/application.cpp.i

.PHONY : src/application.i

# target to preprocess a source file
src/application.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/application.cpp.i
.PHONY : src/application.cpp.i

src/application.s: src/application.cpp.s

.PHONY : src/application.s

# target to generate assembly for a file
src/application.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/application.cpp.s
.PHONY : src/application.cpp.s

src/attractmode.o: src/attractmode.cpp.o

.PHONY : src/attractmode.o

# target to build an object file
src/attractmode.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/attractmode.cpp.o
.PHONY : src/attractmode.cpp.o

src/attractmode.i: src/attractmode.cpp.i

.PHONY : src/attractmode.i

# target to preprocess a source file
src/attractmode.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/attractmode.cpp.i
.PHONY : src/attractmode.cpp.i

src/attractmode.s: src/attractmode.cpp.s

.PHONY : src/attractmode.s

# target to generate assembly for a file
src/attractmode.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/attractmode.cpp.s
.PHONY : src/attractmode.cpp.s

src/attributedisplay.o: src/attributedisplay.cpp.o

.PHONY : src/attributedisplay.o

# target to build an object file
src/attributedisplay.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/attributedisplay.cpp.o
.PHONY : src/attributedisplay.cpp.o

src/attributedisplay.i: src/attributedisplay.cpp.i

.PHONY : src/attributedisplay.i

# target to preprocess a source file
src/attributedisplay.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/attributedisplay.cpp.i
.PHONY : src/attributedisplay.cpp.i

src/attributedisplay.s: src/attributedisplay.cpp.s

.PHONY : src/attributedisplay.s

# target to generate assembly for a file
src/attributedisplay.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/attributedisplay.cpp.s
.PHONY : src/attributedisplay.cpp.s

src/automap.o: src/automap.cpp.o

.PHONY : src/automap.o

# target to build an object file
src/automap.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/automap.cpp.o
.PHONY : src/automap.cpp.o

src/automap.i: src/automap.cpp.i

.PHONY : src/automap.i

# target to preprocess a source file
src/automap.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/automap.cpp.i
.PHONY : src/automap.cpp.i

src/automap.s: src/automap.cpp.s

.PHONY : src/automap.s

# target to generate assembly for a file
src/automap.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/automap.cpp.s
.PHONY : src/automap.cpp.s

src/banner.o: src/banner.cpp.o

.PHONY : src/banner.o

# target to build an object file
src/banner.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/banner.cpp.o
.PHONY : src/banner.cpp.o

src/banner.i: src/banner.cpp.i

.PHONY : src/banner.i

# target to preprocess a source file
src/banner.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/banner.cpp.i
.PHONY : src/banner.cpp.i

src/banner.s: src/banner.cpp.s

.PHONY : src/banner.s

# target to generate assembly for a file
src/banner.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/banner.cpp.s
.PHONY : src/banner.cpp.s

src/castle.o: src/castle.cpp.o

.PHONY : src/castle.o

# target to build an object file
src/castle.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/castle.cpp.o
.PHONY : src/castle.cpp.o

src/castle.i: src/castle.cpp.i

.PHONY : src/castle.i

# target to preprocess a source file
src/castle.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/castle.cpp.i
.PHONY : src/castle.cpp.i

src/castle.s: src/castle.cpp.s

.PHONY : src/castle.s

# target to generate assembly for a file
src/castle.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/castle.cpp.s
.PHONY : src/castle.cpp.s

src/changeclass.o: src/changeclass.cpp.o

.PHONY : src/changeclass.o

# target to build an object file
src/changeclass.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/changeclass.cpp.o
.PHONY : src/changeclass.cpp.o

src/changeclass.i: src/changeclass.cpp.i

.PHONY : src/changeclass.i

# target to preprocess a source file
src/changeclass.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/changeclass.cpp.i
.PHONY : src/changeclass.cpp.i

src/changeclass.s: src/changeclass.cpp.s

.PHONY : src/changeclass.s

# target to generate assembly for a file
src/changeclass.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/changeclass.cpp.s
.PHONY : src/changeclass.cpp.s

src/changename.o: src/changename.cpp.o

.PHONY : src/changename.o

# target to build an object file
src/changename.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/changename.cpp.o
.PHONY : src/changename.cpp.o

src/changename.i: src/changename.cpp.i

.PHONY : src/changename.i

# target to preprocess a source file
src/changename.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/changename.cpp.i
.PHONY : src/changename.cpp.i

src/changename.s: src/changename.cpp.s

.PHONY : src/changename.s

# target to generate assembly for a file
src/changename.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/changename.cpp.s
.PHONY : src/changename.cpp.s

src/character.o: src/character.cpp.o

.PHONY : src/character.o

# target to build an object file
src/character.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/character.cpp.o
.PHONY : src/character.cpp.o

src/character.i: src/character.cpp.i

.PHONY : src/character.i

# target to preprocess a source file
src/character.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/character.cpp.i
.PHONY : src/character.cpp.i

src/character.s: src/character.cpp.s

.PHONY : src/character.s

# target to generate assembly for a file
src/character.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/character.cpp.s
.PHONY : src/character.cpp.s

src/characterpanel.o: src/characterpanel.cpp.o

.PHONY : src/characterpanel.o

# target to build an object file
src/characterpanel.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/characterpanel.cpp.o
.PHONY : src/characterpanel.cpp.o

src/characterpanel.i: src/characterpanel.cpp.i

.PHONY : src/characterpanel.i

# target to preprocess a source file
src/characterpanel.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/characterpanel.cpp.i
.PHONY : src/characterpanel.cpp.i

src/characterpanel.s: src/characterpanel.cpp.s

.PHONY : src/characterpanel.s

# target to generate assembly for a file
src/characterpanel.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/characterpanel.cpp.s
.PHONY : src/characterpanel.cpp.s

src/charactersummary.o: src/charactersummary.cpp.o

.PHONY : src/charactersummary.o

# target to build an object file
src/charactersummary.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/charactersummary.cpp.o
.PHONY : src/charactersummary.cpp.o

src/charactersummary.i: src/charactersummary.cpp.i

.PHONY : src/charactersummary.i

# target to preprocess a source file
src/charactersummary.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/charactersummary.cpp.i
.PHONY : src/charactersummary.cpp.i

src/charactersummary.s: src/charactersummary.cpp.s

.PHONY : src/charactersummary.s

# target to generate assembly for a file
src/charactersummary.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/charactersummary.cpp.s
.PHONY : src/charactersummary.cpp.s

src/compass.o: src/compass.cpp.o

.PHONY : src/compass.o

# target to build an object file
src/compass.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/compass.cpp.o
.PHONY : src/compass.cpp.o

src/compass.i: src/compass.cpp.i

.PHONY : src/compass.i

# target to preprocess a source file
src/compass.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/compass.cpp.i
.PHONY : src/compass.cpp.i

src/compass.s: src/compass.cpp.s

.PHONY : src/compass.s

# target to generate assembly for a file
src/compass.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/compass.cpp.s
.PHONY : src/compass.cpp.s

src/compendium.o: src/compendium.cpp.o

.PHONY : src/compendium.o

# target to build an object file
src/compendium.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/compendium.cpp.o
.PHONY : src/compendium.cpp.o

src/compendium.i: src/compendium.cpp.i

.PHONY : src/compendium.i

# target to preprocess a source file
src/compendium.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/compendium.cpp.i
.PHONY : src/compendium.cpp.i

src/compendium.s: src/compendium.cpp.s

.PHONY : src/compendium.s

# target to generate assembly for a file
src/compendium.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/compendium.cpp.s
.PHONY : src/compendium.cpp.s

src/component.o: src/component.cpp.o

.PHONY : src/component.o

# target to build an object file
src/component.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/component.cpp.o
.PHONY : src/component.cpp.o

src/component.i: src/component.cpp.i

.PHONY : src/component.i

# target to preprocess a source file
src/component.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/component.cpp.i
.PHONY : src/component.cpp.i

src/component.s: src/component.cpp.s

.PHONY : src/component.s

# target to generate assembly for a file
src/component.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/component.cpp.s
.PHONY : src/component.cpp.s

src/config.o: src/config.cpp.o

.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i

.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s

.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/confirm.o: src/confirm.cpp.o

.PHONY : src/confirm.o

# target to build an object file
src/confirm.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/confirm.cpp.o
.PHONY : src/confirm.cpp.o

src/confirm.i: src/confirm.cpp.i

.PHONY : src/confirm.i

# target to preprocess a source file
src/confirm.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/confirm.cpp.i
.PHONY : src/confirm.cpp.i

src/confirm.s: src/confirm.cpp.s

.PHONY : src/confirm.s

# target to generate assembly for a file
src/confirm.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/confirm.cpp.s
.PHONY : src/confirm.cpp.s

src/controloverlay.o: src/controloverlay.cpp.o

.PHONY : src/controloverlay.o

# target to build an object file
src/controloverlay.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/controloverlay.cpp.o
.PHONY : src/controloverlay.cpp.o

src/controloverlay.i: src/controloverlay.cpp.i

.PHONY : src/controloverlay.i

# target to preprocess a source file
src/controloverlay.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/controloverlay.cpp.i
.PHONY : src/controloverlay.cpp.i

src/controloverlay.s: src/controloverlay.cpp.s

.PHONY : src/controloverlay.s

# target to generate assembly for a file
src/controloverlay.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/controloverlay.cpp.s
.PHONY : src/controloverlay.cpp.s

src/create.o: src/create.cpp.o

.PHONY : src/create.o

# target to build an object file
src/create.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/create.cpp.o
.PHONY : src/create.cpp.o

src/create.i: src/create.cpp.i

.PHONY : src/create.i

# target to preprocess a source file
src/create.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/create.cpp.i
.PHONY : src/create.cpp.i

src/create.s: src/create.cpp.s

.PHONY : src/create.s

# target to generate assembly for a file
src/create.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/create.cpp.s
.PHONY : src/create.cpp.s

src/database.o: src/database.cpp.o

.PHONY : src/database.o

# target to build an object file
src/database.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/database.cpp.o
.PHONY : src/database.cpp.o

src/database.i: src/database.cpp.i

.PHONY : src/database.i

# target to preprocess a source file
src/database.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/database.cpp.i
.PHONY : src/database.cpp.i

src/database.s: src/database.cpp.s

.PHONY : src/database.s

# target to generate assembly for a file
src/database.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/database.cpp.s
.PHONY : src/database.cpp.s

src/dialog.o: src/dialog.cpp.o

.PHONY : src/dialog.o

# target to build an object file
src/dialog.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/dialog.cpp.o
.PHONY : src/dialog.cpp.o

src/dialog.i: src/dialog.cpp.i

.PHONY : src/dialog.i

# target to preprocess a source file
src/dialog.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/dialog.cpp.i
.PHONY : src/dialog.cpp.i

src/dialog.s: src/dialog.cpp.s

.PHONY : src/dialog.s

# target to generate assembly for a file
src/dialog.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/dialog.cpp.s
.PHONY : src/dialog.cpp.s

src/display.o: src/display.cpp.o

.PHONY : src/display.o

# target to build an object file
src/display.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/display.cpp.o
.PHONY : src/display.cpp.o

src/display.i: src/display.cpp.i

.PHONY : src/display.i

# target to preprocess a source file
src/display.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/display.cpp.i
.PHONY : src/display.cpp.i

src/display.s: src/display.cpp.s

.PHONY : src/display.s

# target to generate assembly for a file
src/display.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/display.cpp.s
.PHONY : src/display.cpp.s

src/edgeoftown.o: src/edgeoftown.cpp.o

.PHONY : src/edgeoftown.o

# target to build an object file
src/edgeoftown.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/edgeoftown.cpp.o
.PHONY : src/edgeoftown.cpp.o

src/edgeoftown.i: src/edgeoftown.cpp.i

.PHONY : src/edgeoftown.i

# target to preprocess a source file
src/edgeoftown.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/edgeoftown.cpp.i
.PHONY : src/edgeoftown.cpp.i

src/edgeoftown.s: src/edgeoftown.cpp.s

.PHONY : src/edgeoftown.s

# target to generate assembly for a file
src/edgeoftown.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/edgeoftown.cpp.s
.PHONY : src/edgeoftown.cpp.s

src/edit.o: src/edit.cpp.o

.PHONY : src/edit.o

# target to build an object file
src/edit.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/edit.cpp.o
.PHONY : src/edit.cpp.o

src/edit.i: src/edit.cpp.i

.PHONY : src/edit.i

# target to preprocess a source file
src/edit.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/edit.cpp.i
.PHONY : src/edit.cpp.i

src/edit.s: src/edit.cpp.s

.PHONY : src/edit.s

# target to generate assembly for a file
src/edit.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/edit.cpp.s
.PHONY : src/edit.cpp.s

src/engine.o: src/engine.cpp.o

.PHONY : src/engine.o

# target to build an object file
src/engine.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/engine.cpp.o
.PHONY : src/engine.cpp.o

src/engine.i: src/engine.cpp.i

.PHONY : src/engine.i

# target to preprocess a source file
src/engine.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/engine.cpp.i
.PHONY : src/engine.cpp.i

src/engine.s: src/engine.cpp.s

.PHONY : src/engine.s

# target to generate assembly for a file
src/engine.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/engine.cpp.s
.PHONY : src/engine.cpp.s

src/error.o: src/error.cpp.o

.PHONY : src/error.o

# target to build an object file
src/error.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/error.cpp.o
.PHONY : src/error.cpp.o

src/error.i: src/error.cpp.i

.PHONY : src/error.i

# target to preprocess a source file
src/error.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/error.cpp.i
.PHONY : src/error.cpp.i

src/error.s: src/error.cpp.s

.PHONY : src/error.s

# target to generate assembly for a file
src/error.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/error.cpp.s
.PHONY : src/error.cpp.s

src/file.o: src/file.cpp.o

.PHONY : src/file.o

# target to build an object file
src/file.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/file.cpp.o
.PHONY : src/file.cpp.o

src/file.i: src/file.cpp.i

.PHONY : src/file.i

# target to preprocess a source file
src/file.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/file.cpp.i
.PHONY : src/file.cpp.i

src/file.s: src/file.cpp.s

.PHONY : src/file.s

# target to generate assembly for a file
src/file.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/file.cpp.s
.PHONY : src/file.cpp.s

src/font.o: src/font.cpp.o

.PHONY : src/font.o

# target to build an object file
src/font.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/font.cpp.o
.PHONY : src/font.cpp.o

src/font.i: src/font.cpp.i

.PHONY : src/font.i

# target to preprocess a source file
src/font.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/font.cpp.i
.PHONY : src/font.cpp.i

src/font.s: src/font.cpp.s

.PHONY : src/font.s

# target to generate assembly for a file
src/font.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/font.cpp.s
.PHONY : src/font.cpp.s

src/frame.o: src/frame.cpp.o

.PHONY : src/frame.o

# target to build an object file
src/frame.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frame.cpp.o
.PHONY : src/frame.cpp.o

src/frame.i: src/frame.cpp.i

.PHONY : src/frame.i

# target to preprocess a source file
src/frame.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frame.cpp.i
.PHONY : src/frame.cpp.i

src/frame.s: src/frame.cpp.s

.PHONY : src/frame.s

# target to generate assembly for a file
src/frame.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/frame.cpp.s
.PHONY : src/frame.cpp.s

src/game.o: src/game.cpp.o

.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i

.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s

.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/graphics.o: src/graphics.cpp.o

.PHONY : src/graphics.o

# target to build an object file
src/graphics.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/graphics.cpp.o
.PHONY : src/graphics.cpp.o

src/graphics.i: src/graphics.cpp.i

.PHONY : src/graphics.i

# target to preprocess a source file
src/graphics.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/graphics.cpp.i
.PHONY : src/graphics.cpp.i

src/graphics.s: src/graphics.cpp.s

.PHONY : src/graphics.s

# target to generate assembly for a file
src/graphics.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/graphics.cpp.s
.PHONY : src/graphics.cpp.s

src/iconpanel.o: src/iconpanel.cpp.o

.PHONY : src/iconpanel.o

# target to build an object file
src/iconpanel.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/iconpanel.cpp.o
.PHONY : src/iconpanel.cpp.o

src/iconpanel.i: src/iconpanel.cpp.i

.PHONY : src/iconpanel.i

# target to preprocess a source file
src/iconpanel.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/iconpanel.cpp.i
.PHONY : src/iconpanel.cpp.i

src/iconpanel.s: src/iconpanel.cpp.s

.PHONY : src/iconpanel.s

# target to generate assembly for a file
src/iconpanel.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/iconpanel.cpp.s
.PHONY : src/iconpanel.cpp.s

src/iconstore.o: src/iconstore.cpp.o

.PHONY : src/iconstore.o

# target to build an object file
src/iconstore.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/iconstore.cpp.o
.PHONY : src/iconstore.cpp.o

src/iconstore.i: src/iconstore.cpp.i

.PHONY : src/iconstore.i

# target to preprocess a source file
src/iconstore.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/iconstore.cpp.i
.PHONY : src/iconstore.cpp.i

src/iconstore.s: src/iconstore.cpp.s

.PHONY : src/iconstore.s

# target to generate assembly for a file
src/iconstore.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/iconstore.cpp.s
.PHONY : src/iconstore.cpp.s

src/infopanel.o: src/infopanel.cpp.o

.PHONY : src/infopanel.o

# target to build an object file
src/infopanel.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/infopanel.cpp.o
.PHONY : src/infopanel.cpp.o

src/infopanel.i: src/infopanel.cpp.i

.PHONY : src/infopanel.i

# target to preprocess a source file
src/infopanel.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/infopanel.cpp.i
.PHONY : src/infopanel.cpp.i

src/infopanel.s: src/infopanel.cpp.s

.PHONY : src/infopanel.s

# target to generate assembly for a file
src/infopanel.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/infopanel.cpp.s
.PHONY : src/infopanel.cpp.s

src/inn.o: src/inn.cpp.o

.PHONY : src/inn.o

# target to build an object file
src/inn.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/inn.cpp.o
.PHONY : src/inn.cpp.o

src/inn.i: src/inn.cpp.i

.PHONY : src/inn.i

# target to preprocess a source file
src/inn.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/inn.cpp.i
.PHONY : src/inn.cpp.i

src/inn.s: src/inn.cpp.s

.PHONY : src/inn.s

# target to generate assembly for a file
src/inn.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/inn.cpp.s
.PHONY : src/inn.cpp.s

src/input.o: src/input.cpp.o

.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i

.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s

.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/inspect.o: src/inspect.cpp.o

.PHONY : src/inspect.o

# target to build an object file
src/inspect.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/inspect.cpp.o
.PHONY : src/inspect.cpp.o

src/inspect.i: src/inspect.cpp.i

.PHONY : src/inspect.i

# target to preprocess a source file
src/inspect.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/inspect.cpp.i
.PHONY : src/inspect.cpp.i

src/inspect.s: src/inspect.cpp.s

.PHONY : src/inspect.s

# target to generate assembly for a file
src/inspect.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/inspect.cpp.s
.PHONY : src/inspect.cpp.s

src/keyboard.o: src/keyboard.cpp.o

.PHONY : src/keyboard.o

# target to build an object file
src/keyboard.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/keyboard.cpp.o
.PHONY : src/keyboard.cpp.o

src/keyboard.i: src/keyboard.cpp.i

.PHONY : src/keyboard.i

# target to preprocess a source file
src/keyboard.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/keyboard.cpp.i
.PHONY : src/keyboard.cpp.i

src/keyboard.s: src/keyboard.cpp.s

.PHONY : src/keyboard.s

# target to generate assembly for a file
src/keyboard.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/keyboard.cpp.s
.PHONY : src/keyboard.cpp.s

src/layout.o: src/layout.cpp.o

.PHONY : src/layout.o

# target to build an object file
src/layout.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/layout.cpp.o
.PHONY : src/layout.cpp.o

src/layout.i: src/layout.cpp.i

.PHONY : src/layout.i

# target to preprocess a source file
src/layout.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/layout.cpp.i
.PHONY : src/layout.cpp.i

src/layout.s: src/layout.cpp.s

.PHONY : src/layout.s

# target to generate assembly for a file
src/layout.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/layout.cpp.s
.PHONY : src/layout.cpp.s

src/legate.o: src/legate.cpp.o

.PHONY : src/legate.o

# target to build an object file
src/legate.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/legate.cpp.o
.PHONY : src/legate.cpp.o

src/legate.i: src/legate.cpp.i

.PHONY : src/legate.i

# target to preprocess a source file
src/legate.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/legate.cpp.i
.PHONY : src/legate.cpp.i

src/legate.s: src/legate.cpp.s

.PHONY : src/legate.s

# target to generate assembly for a file
src/legate.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/legate.cpp.s
.PHONY : src/legate.cpp.s

src/license.o: src/license.cpp.o

.PHONY : src/license.o

# target to build an object file
src/license.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/license.cpp.o
.PHONY : src/license.cpp.o

src/license.i: src/license.cpp.i

.PHONY : src/license.i

# target to preprocess a source file
src/license.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/license.cpp.i
.PHONY : src/license.cpp.i

src/license.s: src/license.cpp.s

.PHONY : src/license.s

# target to generate assembly for a file
src/license.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/license.cpp.s
.PHONY : src/license.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mainmenu.o: src/mainmenu.cpp.o

.PHONY : src/mainmenu.o

# target to build an object file
src/mainmenu.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/mainmenu.cpp.o
.PHONY : src/mainmenu.cpp.o

src/mainmenu.i: src/mainmenu.cpp.i

.PHONY : src/mainmenu.i

# target to preprocess a source file
src/mainmenu.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/mainmenu.cpp.i
.PHONY : src/mainmenu.cpp.i

src/mainmenu.s: src/mainmenu.cpp.s

.PHONY : src/mainmenu.s

# target to generate assembly for a file
src/mainmenu.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/mainmenu.cpp.s
.PHONY : src/mainmenu.cpp.s

src/manage.o: src/manage.cpp.o

.PHONY : src/manage.o

# target to build an object file
src/manage.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/manage.cpp.o
.PHONY : src/manage.cpp.o

src/manage.i: src/manage.cpp.i

.PHONY : src/manage.i

# target to preprocess a source file
src/manage.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/manage.cpp.i
.PHONY : src/manage.cpp.i

src/manage.s: src/manage.cpp.s

.PHONY : src/manage.s

# target to generate assembly for a file
src/manage.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/manage.cpp.s
.PHONY : src/manage.cpp.s

src/map.o: src/map.cpp.o

.PHONY : src/map.o

# target to build an object file
src/map.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/map.cpp.o
.PHONY : src/map.cpp.o

src/map.i: src/map.cpp.i

.PHONY : src/map.i

# target to preprocess a source file
src/map.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/map.cpp.i
.PHONY : src/map.cpp.i

src/map.s: src/map.cpp.s

.PHONY : src/map.s

# target to generate assembly for a file
src/map.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/map.cpp.s
.PHONY : src/map.cpp.s

src/menu.o: src/menu.cpp.o

.PHONY : src/menu.o

# target to build an object file
src/menu.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/menu.cpp.o
.PHONY : src/menu.cpp.o

src/menu.i: src/menu.cpp.i

.PHONY : src/menu.i

# target to preprocess a source file
src/menu.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/menu.cpp.i
.PHONY : src/menu.cpp.i

src/menu.s: src/menu.cpp.s

.PHONY : src/menu.s

# target to generate assembly for a file
src/menu.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/menu.cpp.s
.PHONY : src/menu.cpp.s

src/options.o: src/options.cpp.o

.PHONY : src/options.o

# target to build an object file
src/options.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/options.cpp.o
.PHONY : src/options.cpp.o

src/options.i: src/options.cpp.i

.PHONY : src/options.i

# target to preprocess a source file
src/options.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/options.cpp.i
.PHONY : src/options.cpp.i

src/options.s: src/options.cpp.s

.PHONY : src/options.s

# target to generate assembly for a file
src/options.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/options.cpp.s
.PHONY : src/options.cpp.s

src/platform.o: src/platform.cpp.o

.PHONY : src/platform.o

# target to build an object file
src/platform.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/platform.cpp.o
.PHONY : src/platform.cpp.o

src/platform.i: src/platform.cpp.i

.PHONY : src/platform.i

# target to preprocess a source file
src/platform.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/platform.cpp.i
.PHONY : src/platform.cpp.i

src/platform.s: src/platform.cpp.s

.PHONY : src/platform.s

# target to generate assembly for a file
src/platform.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/platform.cpp.s
.PHONY : src/platform.cpp.s

src/random.o: src/random.cpp.o

.PHONY : src/random.o

# target to build an object file
src/random.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/random.cpp.o
.PHONY : src/random.cpp.o

src/random.i: src/random.cpp.i

.PHONY : src/random.i

# target to preprocess a source file
src/random.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/random.cpp.i
.PHONY : src/random.cpp.i

src/random.s: src/random.cpp.s

.PHONY : src/random.s

# target to generate assembly for a file
src/random.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/random.cpp.s
.PHONY : src/random.cpp.s

src/render.o: src/render.cpp.o

.PHONY : src/render.o

# target to build an object file
src/render.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/render.cpp.o
.PHONY : src/render.cpp.o

src/render.i: src/render.cpp.i

.PHONY : src/render.i

# target to preprocess a source file
src/render.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/render.cpp.i
.PHONY : src/render.cpp.i

src/render.s: src/render.cpp.s

.PHONY : src/render.s

# target to generate assembly for a file
src/render.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/render.cpp.s
.PHONY : src/render.cpp.s

src/reorder.o: src/reorder.cpp.o

.PHONY : src/reorder.o

# target to build an object file
src/reorder.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/reorder.cpp.o
.PHONY : src/reorder.cpp.o

src/reorder.i: src/reorder.cpp.i

.PHONY : src/reorder.i

# target to preprocess a source file
src/reorder.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/reorder.cpp.i
.PHONY : src/reorder.cpp.i

src/reorder.s: src/reorder.cpp.s

.PHONY : src/reorder.s

# target to generate assembly for a file
src/reorder.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/reorder.cpp.s
.PHONY : src/reorder.cpp.s

src/resourcemanager.o: src/resourcemanager.cpp.o

.PHONY : src/resourcemanager.o

# target to build an object file
src/resourcemanager.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resourcemanager.cpp.o
.PHONY : src/resourcemanager.cpp.o

src/resourcemanager.i: src/resourcemanager.cpp.i

.PHONY : src/resourcemanager.i

# target to preprocess a source file
src/resourcemanager.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resourcemanager.cpp.i
.PHONY : src/resourcemanager.cpp.i

src/resourcemanager.s: src/resourcemanager.cpp.s

.PHONY : src/resourcemanager.s

# target to generate assembly for a file
src/resourcemanager.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/resourcemanager.cpp.s
.PHONY : src/resourcemanager.cpp.s

src/roster.o: src/roster.cpp.o

.PHONY : src/roster.o

# target to build an object file
src/roster.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/roster.cpp.o
.PHONY : src/roster.cpp.o

src/roster.i: src/roster.cpp.i

.PHONY : src/roster.i

# target to preprocess a source file
src/roster.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/roster.cpp.i
.PHONY : src/roster.cpp.i

src/roster.s: src/roster.cpp.s

.PHONY : src/roster.s

# target to generate assembly for a file
src/roster.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/roster.cpp.s
.PHONY : src/roster.cpp.s

src/shop.o: src/shop.cpp.o

.PHONY : src/shop.o

# target to build an object file
src/shop.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/shop.cpp.o
.PHONY : src/shop.cpp.o

src/shop.i: src/shop.cpp.i

.PHONY : src/shop.i

# target to preprocess a source file
src/shop.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/shop.cpp.i
.PHONY : src/shop.cpp.i

src/shop.s: src/shop.cpp.s

.PHONY : src/shop.s

# target to generate assembly for a file
src/shop.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/shop.cpp.s
.PHONY : src/shop.cpp.s

src/spellpanel.o: src/spellpanel.cpp.o

.PHONY : src/spellpanel.o

# target to build an object file
src/spellpanel.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/spellpanel.cpp.o
.PHONY : src/spellpanel.cpp.o

src/spellpanel.i: src/spellpanel.cpp.i

.PHONY : src/spellpanel.i

# target to preprocess a source file
src/spellpanel.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/spellpanel.cpp.i
.PHONY : src/spellpanel.cpp.i

src/spellpanel.s: src/spellpanel.cpp.s

.PHONY : src/spellpanel.s

# target to generate assembly for a file
src/spellpanel.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/spellpanel.cpp.s
.PHONY : src/spellpanel.cpp.s

src/splash.o: src/splash.cpp.o

.PHONY : src/splash.o

# target to build an object file
src/splash.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/splash.cpp.o
.PHONY : src/splash.cpp.o

src/splash.i: src/splash.cpp.i

.PHONY : src/splash.i

# target to preprocess a source file
src/splash.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/splash.cpp.i
.PHONY : src/splash.cpp.i

src/splash.s: src/splash.cpp.s

.PHONY : src/splash.s

# target to generate assembly for a file
src/splash.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/splash.cpp.s
.PHONY : src/splash.cpp.s

src/state.o: src/state.cpp.o

.PHONY : src/state.o

# target to build an object file
src/state.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/state.cpp.o
.PHONY : src/state.cpp.o

src/state.i: src/state.cpp.i

.PHONY : src/state.i

# target to preprocess a source file
src/state.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/state.cpp.i
.PHONY : src/state.cpp.i

src/state.s: src/state.cpp.s

.PHONY : src/state.s

# target to generate assembly for a file
src/state.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/state.cpp.s
.PHONY : src/state.cpp.s

src/statusbar.o: src/statusbar.cpp.o

.PHONY : src/statusbar.o

# target to build an object file
src/statusbar.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/statusbar.cpp.o
.PHONY : src/statusbar.cpp.o

src/statusbar.i: src/statusbar.cpp.i

.PHONY : src/statusbar.i

# target to preprocess a source file
src/statusbar.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/statusbar.cpp.i
.PHONY : src/statusbar.cpp.i

src/statusbar.s: src/statusbar.cpp.s

.PHONY : src/statusbar.s

# target to generate assembly for a file
src/statusbar.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/statusbar.cpp.s
.PHONY : src/statusbar.cpp.s

src/string.o: src/string.cpp.o

.PHONY : src/string.o

# target to build an object file
src/string.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/string.cpp.o
.PHONY : src/string.cpp.o

src/string.i: src/string.cpp.i

.PHONY : src/string.i

# target to preprocess a source file
src/string.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/string.cpp.i
.PHONY : src/string.cpp.i

src/string.s: src/string.cpp.s

.PHONY : src/string.s

# target to generate assembly for a file
src/string.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/string.cpp.s
.PHONY : src/string.cpp.s

src/system.o: src/system.cpp.o

.PHONY : src/system.o

# target to build an object file
src/system.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/system.cpp.o
.PHONY : src/system.cpp.o

src/system.i: src/system.cpp.i

.PHONY : src/system.i

# target to preprocess a source file
src/system.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/system.cpp.i
.PHONY : src/system.cpp.i

src/system.s: src/system.cpp.s

.PHONY : src/system.s

# target to generate assembly for a file
src/system.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/system.cpp.s
.PHONY : src/system.cpp.s

src/tavern.o: src/tavern.cpp.o

.PHONY : src/tavern.o

# target to build an object file
src/tavern.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/tavern.cpp.o
.PHONY : src/tavern.cpp.o

src/tavern.i: src/tavern.cpp.i

.PHONY : src/tavern.i

# target to preprocess a source file
src/tavern.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/tavern.cpp.i
.PHONY : src/tavern.cpp.i

src/tavern.s: src/tavern.cpp.s

.PHONY : src/tavern.s

# target to generate assembly for a file
src/tavern.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/tavern.cpp.s
.PHONY : src/tavern.cpp.s

src/temple.o: src/temple.cpp.o

.PHONY : src/temple.o

# target to build an object file
src/temple.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/temple.cpp.o
.PHONY : src/temple.cpp.o

src/temple.i: src/temple.cpp.i

.PHONY : src/temple.i

# target to preprocess a source file
src/temple.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/temple.cpp.i
.PHONY : src/temple.cpp.i

src/temple.s: src/temple.cpp.s

.PHONY : src/temple.s

# target to generate assembly for a file
src/temple.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/temple.cpp.s
.PHONY : src/temple.cpp.s

src/text.o: src/text.cpp.o

.PHONY : src/text.o

# target to build an object file
src/text.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/text.cpp.o
.PHONY : src/text.cpp.o

src/text.i: src/text.cpp.i

.PHONY : src/text.i

# target to preprocess a source file
src/text.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/text.cpp.i
.PHONY : src/text.cpp.i

src/text.s: src/text.cpp.s

.PHONY : src/text.s

# target to generate assembly for a file
src/text.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/text.cpp.s
.PHONY : src/text.cpp.s

src/textfile.o: src/textfile.cpp.o

.PHONY : src/textfile.o

# target to build an object file
src/textfile.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/textfile.cpp.o
.PHONY : src/textfile.cpp.o

src/textfile.i: src/textfile.cpp.i

.PHONY : src/textfile.i

# target to preprocess a source file
src/textfile.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/textfile.cpp.i
.PHONY : src/textfile.cpp.i

src/textfile.s: src/textfile.cpp.s

.PHONY : src/textfile.s

# target to generate assembly for a file
src/textfile.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/textfile.cpp.s
.PHONY : src/textfile.cpp.s

src/texturestore.o: src/texturestore.cpp.o

.PHONY : src/texturestore.o

# target to build an object file
src/texturestore.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/texturestore.cpp.o
.PHONY : src/texturestore.cpp.o

src/texturestore.i: src/texturestore.cpp.i

.PHONY : src/texturestore.i

# target to preprocess a source file
src/texturestore.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/texturestore.cpp.i
.PHONY : src/texturestore.cpp.i

src/texturestore.s: src/texturestore.cpp.s

.PHONY : src/texturestore.s

# target to generate assembly for a file
src/texturestore.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/texturestore.cpp.s
.PHONY : src/texturestore.cpp.s

src/tile.o: src/tile.cpp.o

.PHONY : src/tile.o

# target to build an object file
src/tile.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/tile.cpp.o
.PHONY : src/tile.cpp.o

src/tile.i: src/tile.cpp.i

.PHONY : src/tile.i

# target to preprocess a source file
src/tile.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/tile.cpp.i
.PHONY : src/tile.cpp.i

src/tile.s: src/tile.cpp.s

.PHONY : src/tile.s

# target to generate assembly for a file
src/tile.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/tile.cpp.s
.PHONY : src/tile.cpp.s

src/training.o: src/training.cpp.o

.PHONY : src/training.o

# target to build an object file
src/training.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/training.cpp.o
.PHONY : src/training.cpp.o

src/training.i: src/training.cpp.i

.PHONY : src/training.i

# target to preprocess a source file
src/training.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/training.cpp.i
.PHONY : src/training.cpp.i

src/training.s: src/training.cpp.s

.PHONY : src/training.s

# target to generate assembly for a file
src/training.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/training.cpp.s
.PHONY : src/training.cpp.s

src/view.o: src/view.cpp.o

.PHONY : src/view.o

# target to build an object file
src/view.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/view.cpp.o
.PHONY : src/view.cpp.o

src/view.i: src/view.cpp.i

.PHONY : src/view.i

# target to preprocess a source file
src/view.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/view.cpp.i
.PHONY : src/view.cpp.i

src/view.s: src/view.cpp.s

.PHONY : src/view.s

# target to generate assembly for a file
src/view.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/view.cpp.s
.PHONY : src/view.cpp.s

src/window.o: src/window.cpp.o

.PHONY : src/window.o

# target to build an object file
src/window.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/window.cpp.o
.PHONY : src/window.cpp.o

src/window.i: src/window.cpp.i

.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s

.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

src/world.o: src/world.cpp.o

.PHONY : src/world.o

# target to build an object file
src/world.cpp.o:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/world.cpp.o
.PHONY : src/world.cpp.o

src/world.i: src/world.cpp.i

.PHONY : src/world.i

# target to preprocess a source file
src/world.cpp.i:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/world.cpp.i
.PHONY : src/world.cpp.i

src/world.s: src/world.cpp.s

.PHONY : src/world.s

# target to generate assembly for a file
src/world.cpp.s:
	$(MAKE) -f CMakeFiles/sorcery.dir/build.make CMakeFiles/sorcery.dir/src/world.cpp.s
.PHONY : src/world.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... package"
	@echo "... sorcery"
	@echo "... src/allocatepanel.o"
	@echo "... src/allocatepanel.i"
	@echo "... src/allocatepanel.s"
	@echo "... src/animation.o"
	@echo "... src/animation.i"
	@echo "... src/animation.s"
	@echo "... src/application.o"
	@echo "... src/application.i"
	@echo "... src/application.s"
	@echo "... src/attractmode.o"
	@echo "... src/attractmode.i"
	@echo "... src/attractmode.s"
	@echo "... src/attributedisplay.o"
	@echo "... src/attributedisplay.i"
	@echo "... src/attributedisplay.s"
	@echo "... src/automap.o"
	@echo "... src/automap.i"
	@echo "... src/automap.s"
	@echo "... src/banner.o"
	@echo "... src/banner.i"
	@echo "... src/banner.s"
	@echo "... src/castle.o"
	@echo "... src/castle.i"
	@echo "... src/castle.s"
	@echo "... src/changeclass.o"
	@echo "... src/changeclass.i"
	@echo "... src/changeclass.s"
	@echo "... src/changename.o"
	@echo "... src/changename.i"
	@echo "... src/changename.s"
	@echo "... src/character.o"
	@echo "... src/character.i"
	@echo "... src/character.s"
	@echo "... src/characterpanel.o"
	@echo "... src/characterpanel.i"
	@echo "... src/characterpanel.s"
	@echo "... src/charactersummary.o"
	@echo "... src/charactersummary.i"
	@echo "... src/charactersummary.s"
	@echo "... src/compass.o"
	@echo "... src/compass.i"
	@echo "... src/compass.s"
	@echo "... src/compendium.o"
	@echo "... src/compendium.i"
	@echo "... src/compendium.s"
	@echo "... src/component.o"
	@echo "... src/component.i"
	@echo "... src/component.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/confirm.o"
	@echo "... src/confirm.i"
	@echo "... src/confirm.s"
	@echo "... src/controloverlay.o"
	@echo "... src/controloverlay.i"
	@echo "... src/controloverlay.s"
	@echo "... src/create.o"
	@echo "... src/create.i"
	@echo "... src/create.s"
	@echo "... src/database.o"
	@echo "... src/database.i"
	@echo "... src/database.s"
	@echo "... src/dialog.o"
	@echo "... src/dialog.i"
	@echo "... src/dialog.s"
	@echo "... src/display.o"
	@echo "... src/display.i"
	@echo "... src/display.s"
	@echo "... src/edgeoftown.o"
	@echo "... src/edgeoftown.i"
	@echo "... src/edgeoftown.s"
	@echo "... src/edit.o"
	@echo "... src/edit.i"
	@echo "... src/edit.s"
	@echo "... src/engine.o"
	@echo "... src/engine.i"
	@echo "... src/engine.s"
	@echo "... src/error.o"
	@echo "... src/error.i"
	@echo "... src/error.s"
	@echo "... src/file.o"
	@echo "... src/file.i"
	@echo "... src/file.s"
	@echo "... src/font.o"
	@echo "... src/font.i"
	@echo "... src/font.s"
	@echo "... src/frame.o"
	@echo "... src/frame.i"
	@echo "... src/frame.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/graphics.o"
	@echo "... src/graphics.i"
	@echo "... src/graphics.s"
	@echo "... src/iconpanel.o"
	@echo "... src/iconpanel.i"
	@echo "... src/iconpanel.s"
	@echo "... src/iconstore.o"
	@echo "... src/iconstore.i"
	@echo "... src/iconstore.s"
	@echo "... src/infopanel.o"
	@echo "... src/infopanel.i"
	@echo "... src/infopanel.s"
	@echo "... src/inn.o"
	@echo "... src/inn.i"
	@echo "... src/inn.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/inspect.o"
	@echo "... src/inspect.i"
	@echo "... src/inspect.s"
	@echo "... src/keyboard.o"
	@echo "... src/keyboard.i"
	@echo "... src/keyboard.s"
	@echo "... src/layout.o"
	@echo "... src/layout.i"
	@echo "... src/layout.s"
	@echo "... src/legate.o"
	@echo "... src/legate.i"
	@echo "... src/legate.s"
	@echo "... src/license.o"
	@echo "... src/license.i"
	@echo "... src/license.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mainmenu.o"
	@echo "... src/mainmenu.i"
	@echo "... src/mainmenu.s"
	@echo "... src/manage.o"
	@echo "... src/manage.i"
	@echo "... src/manage.s"
	@echo "... src/map.o"
	@echo "... src/map.i"
	@echo "... src/map.s"
	@echo "... src/menu.o"
	@echo "... src/menu.i"
	@echo "... src/menu.s"
	@echo "... src/options.o"
	@echo "... src/options.i"
	@echo "... src/options.s"
	@echo "... src/platform.o"
	@echo "... src/platform.i"
	@echo "... src/platform.s"
	@echo "... src/random.o"
	@echo "... src/random.i"
	@echo "... src/random.s"
	@echo "... src/render.o"
	@echo "... src/render.i"
	@echo "... src/render.s"
	@echo "... src/reorder.o"
	@echo "... src/reorder.i"
	@echo "... src/reorder.s"
	@echo "... src/resourcemanager.o"
	@echo "... src/resourcemanager.i"
	@echo "... src/resourcemanager.s"
	@echo "... src/roster.o"
	@echo "... src/roster.i"
	@echo "... src/roster.s"
	@echo "... src/shop.o"
	@echo "... src/shop.i"
	@echo "... src/shop.s"
	@echo "... src/spellpanel.o"
	@echo "... src/spellpanel.i"
	@echo "... src/spellpanel.s"
	@echo "... src/splash.o"
	@echo "... src/splash.i"
	@echo "... src/splash.s"
	@echo "... src/state.o"
	@echo "... src/state.i"
	@echo "... src/state.s"
	@echo "... src/statusbar.o"
	@echo "... src/statusbar.i"
	@echo "... src/statusbar.s"
	@echo "... src/string.o"
	@echo "... src/string.i"
	@echo "... src/string.s"
	@echo "... src/system.o"
	@echo "... src/system.i"
	@echo "... src/system.s"
	@echo "... src/tavern.o"
	@echo "... src/tavern.i"
	@echo "... src/tavern.s"
	@echo "... src/temple.o"
	@echo "... src/temple.i"
	@echo "... src/temple.s"
	@echo "... src/text.o"
	@echo "... src/text.i"
	@echo "... src/text.s"
	@echo "... src/textfile.o"
	@echo "... src/textfile.i"
	@echo "... src/textfile.s"
	@echo "... src/texturestore.o"
	@echo "... src/texturestore.i"
	@echo "... src/texturestore.s"
	@echo "... src/tile.o"
	@echo "... src/tile.i"
	@echo "... src/tile.s"
	@echo "... src/training.o"
	@echo "... src/training.i"
	@echo "... src/training.s"
	@echo "... src/view.o"
	@echo "... src/view.i"
	@echo "... src/view.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
	@echo "... src/world.o"
	@echo "... src/world.i"
	@echo "... src/world.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

