# Work exclusively in a disposable directory inside this test's build tree.
set(SORCERY_SOURCE_SAVES "${TEST_ROOT}/seed")
set(SORCERY_DEST_SAVES "${TEST_ROOT}/runtime")
file(MAKE_DIRECTORY "${SORCERY_SOURCE_SAVES}")
file(WRITE "${SORCERY_SOURCE_SAVES}/game.json" "sample game")
include("${PROJECT_SOURCE}/cmake/InitializeSaves.cmake")
if(NOT IS_DIRECTORY "${SORCERY_DEST_SAVES}/characters" OR
   NOT IS_DIRECTORY "${SORCERY_DEST_SAVES}/states")
    message(FATAL_ERROR "Fresh build did not create required save directories")
endif()
file(READ "${SORCERY_DEST_SAVES}/game.json" initial)
if(NOT initial STREQUAL "sample game")
    message(FATAL_ERROR "Fresh build did not seed its save")
endif()
file(WRITE "${SORCERY_DEST_SAVES}/game.json" "player progress")
file(WRITE "${SORCERY_DEST_SAVES}/states/save_state.b64" "quicksave")
include("${PROJECT_SOURCE}/cmake/InitializeSaves.cmake")
file(READ "${SORCERY_DEST_SAVES}/game.json" progress)
file(READ "${SORCERY_DEST_SAVES}/states/save_state.b64" quicksave)
if(NOT progress STREQUAL "player progress" OR NOT quicksave STREQUAL "quicksave")
    message(FATAL_ERROR "Rebuild replaced player progress")
endif()
# Restore the seed value so this check can run repeatedly without deleting data.
file(WRITE "${SORCERY_DEST_SAVES}/game.json" "sample game")
